<div class="modal fade" tabindex="-1" role="dialog">
    <?php 
        $form->setAttribute('action', '/clientes/ver/'.$entity->getIdcliente().'/expedientes/ver/'.$entity->getIdexpediente().'/nuevoservicio');
        $form->setAttribute('enctype', 'multipart/form-data');

        echo $this->form()->openTag($form); 
    ?>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">NUEVO SERVICIO</h4>
      </div>
      <div class="modal-body">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-6">
                    <div class="row-fluid">
                        <div class="form-group">
                            <?php echo $this->formHidden($form->get('idexpediente')) ?>
                            <?php echo $this->formLabel($form->get('expedienteservicio_fecha')) ?> 
                             <span class="help req">*</span>
                            <div class="controls">
                                <div class="input-with-icon  right">
                                    <div class="input-append success date width-93">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('expedienteservicio_fecha')) ?>  
                                        <span class="add-on"><span class="arrow"></span><i class="fa fa-th"></i></span> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-6">
                    <div class="row-fluid">
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('servicio_medio')) ?>  
                            <span class="help req">*</span>
                            <div class="input-with-icon right" style="margin-top: 7px;">
                                <i class=""></i>
                                <?php echo $this->formSelect($form->get('servicio_medio')) ?>
                            </div>
                            <span class="error"></span>
                        </div>
                    </div>
                </div>
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="row-fluid">
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('idservicio')) ?>  
                            <span class="help req">*</span>
                            <div class="input-with-icon  right">
                                <i class=""></i>
                                <?php echo $this->formSelect($form->get('idservicio')) ?>
                            </div>
                            <span class="error"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button btn-action="submit" type="submit" class="btn btn-success"><i class="fa fa-save"></i> Guardar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
  </form>
</div><!-- /.modal -->

