<div class="list_container">
    <ul class="breadcrumb">
        <li>
            <p>Catalogo</p>
        </li>
        <li>
            <a href="javascript:;">Gastos facturación</a>
        </li>
        <li>
            <a class="active" href="/catalogo/gastos">Conceptos</a>
        </li>
    </ul>
    <div class="page-title">
        <h3><span class="semi-bold">CONCEPTOS</span></h3>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-title no-border">
                    <div class="tools">
                        <a id="user-options" class="dropdown-toggle pull-right " href="#" data-toggle="dropdown" style="background: none">
                            <div class="iconset top-settings-dark "></div>
                        </a>
                        <ul class="dropdown-menu pull-right" aria-labelledby="user-options" role="menu">
                            <li>
                                <a style="background: none"href="/catalogo/gastos/nuevo"><i class="fa fa-plus"></i> Registro concepto</a>
                            </li>
                        </ul>
                    </div>
                    <br>
                </div>
                <div class="grid-body no-border">
                    <table id="example" class="table">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Categoria</th>
                                <th>Descripción</th>
                                <th>IVA</th>
                                <th>Opciones</th>
                            </tr>
                    </thead>
                    <tbody>
                        
                    </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!--CUSTOM SCRIPT-->
<script src="/js/admin/catalogo/gastos.js"></script>
<script>
    $(document).ready(function() {
        var gastos = $('.list_container').gastos({successMessages:<?php echo $successMessages?>});
        gastos.list();
    }); 
</script>

