<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

<script src="js/servicios.js"></script>
<script src="js/jquery-ui.js"></script>

<script>

  </script>


	  

	
	 

<div class="page-header row"></div>

<div class="row top">
	
	<div class="col-lg-12">
		<h2>Heading 2</h2>
		<h5 class="justifyText">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est quasi ab rem quibusdam, reprehenderit quis veniam dolorum qui, aliquid id voluptatibus labore incidunt ducimus doloribus nostrum ex recusandae laboriosam sint?</h5>
	
	</div>
	
</div>
<div class="row top">





	
	<div class="hidden-xs">

		<img class="img-responsive" id="imgTransportes" src="/img/Servicios/Servicios-transporte.jpg"  usemap="#mapTransportes" alt="" />
	  	<div id="detalleMaritimo">
			<div class="detalle-content">
				<span id="maritimoClose"class="glyphicon glyphicon-remove pull-right icon-close" aria-hidden="true"></span>
				<br>
		    	<h4><strong>TRANSPORTE MARÍTIMO</strong></h4>
				<br>
				Servicios adecuados a las necesidades de cada tipo de carga, cliente y/o negociación de compra-venta.
				<br>
				Atención personalizada 24/7.
				<br>
				Oficinas propias en las principales ciudades de China.
				<br>
				Servicios de Despacho Aduanal en Origen y/o Destino.
				<br>
				Servicio Web Tracking.
				<br>
				Cotizaciones en menos de 24 horas (Puerto-Puerto).
				<br>
				Servicio FCL, LCL, Break Bulk, RoRo, Chartering y Refrigerados.
				<br>
				Proyectos Especiales.
				<br>
				Fletamento de Buques.
			</div>
	  	</div>
	  	<div id="detalleTerrestre">
			<div class="detalle-content">
				<span id="terrestreClose"class="glyphicon glyphicon-remove pull-right icon-close" aria-hidden="true"></span>
				<br>
		    	<h4><strong>TRANSPORTE MARÍTIMO</strong></h4>
				<br>
				Servicios adecuados a las necesidades de cada tipo de carga, cliente y/o negociación de compra-venta.
				<br>
				Atención personalizada 24/7.
				<br>
				Oficinas propias en las principales ciudades de China.
				<br>
				Servicios de Despacho Aduanal en Origen y/o Destino.
				<br>
				Servicio Web Tracking.
				<br>
				Cotizaciones en menos de 24 horas (Puerto-Puerto).
				<br>
				Servicio FCL, LCL, Break Bulk, RoRo, Chartering y Refrigerados.
				<br>
				Proyectos Especiales.
				<br>
				Fletamento de Buques.
			</div>
	  	</div>

	  	<div id="detalleAereo">
			<div class="detalle-content">
				<span id="aereoClose"class="glyphicon glyphicon-remove pull-right icon-close" aria-hidden="true"></span>
				<br>
		    	<h4><strong>TRANSPORTE MARÍTIMO</strong></h4>
				<br>
				Servicios adecuados a las necesidades de cada tipo de carga, cliente y/o negociación de compra-venta.
				<br>
				Atención personalizada 24/7.
				<br>
				Oficinas propias en las principales ciudades de China.
				<br>
				Servicios de Despacho Aduanal en Origen y/o Destino.
				<br>
				Servicio Web Tracking.
				<br>
				Cotizaciones en menos de 24 horas (Puerto-Puerto).
				<br>
				Servicio FCL, LCL, Break Bulk, RoRo, Chartering y Refrigerados.
				<br>
				Proyectos Especiales.
				<br>
				Fletamento de Buques.
			</div>
	  	</div>
	  	

		<map name="mapTransportes">

			<area  id="btnMaritimo"  shape="rect" coords="0,253,335,335"        />
			<area  id="btnAereo"     shape="rect" coords="335,254,667,336"      />
			<area  id="btnTerrestre" shape="rect" coords="666,253,1000,336"     />
			
		</map>

		<div id="collapsibleUno" class=" collapse"  >
			<div id="collapsiblePanel" class="alert alert-maritimo" role="alert">
				
				<strong>TRANSPORTE MARÍTIMO</strong>
	 			<br>
				Servicios adecuados a las necesidades de cada tipo de carga, cliente y/o negociación de compra-venta.
				<br>
				Atención personalizada 24/7.
				<br>
				Oficinas propias en las principales ciudades de China.
				<br>
				Servicios de Despacho Aduanal en Origen y/o Destino.
				<br>
				Servicio Web Tracking.
				<br>
				Cotizaciones en menos de 24 horas (Puerto-Puerto).
				<br>
				Servicio FCL, LCL, Break Bulk, RoRo, Chartering y Refrigerados.
				<br>
				Proyectos Especiales.
				<br>
				Fletamento de Buques.

			</div>
		</div>


	</div>

	<div class="hidden visible-xs">

		<img class="img-responsive col-xs-8 col-xs-offset-2 img-rounded" id="imgTransportes " src="/img/Servicios/Movil/transporte1.jpg"  usemap="#transporte1" alt="" />
		<img class="img-responsive col-xs-8 col-xs-offset-2 top img-rounded" id="imgTransportes2" src="/img/Servicios/Movil/transporte2.jpg"  usemap="#transporte2" alt="" />
		<img class="img-responsive col-xs-8 col-xs-offset-2 top img-rounded" id="imgTransportes3" src="/img/Servicios/Movil/transporte3.jpg"  usemap="#transporte3" alt="" />


		<map name="transporte1">
			<area  alt="" title="" href="#test1" shape="rect" coords="0,253,335,335"  target="_self"    />
		</map>
		<map name="transporte2">
			<area  alt="" title="" href="#test2" shape="rect" coords="0,253,335,335"  target="_self"    />
		</map>
		<map name="transporte3">
			<area  alt="" title="" href="#test3" shape="rect" coords="0,253,335,335"  target="_self"    />
		</map>
	</div>

</div>

<div class="row top ">
	
	<div class="col-lg-12">
		<h2>Heading 2</h2>
		<h5 class="justifyText">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est quasi ab rem quibusdam, reprehenderit quis veniam dolorum qui, aliquid id voluptatibus labore incidunt ducimus doloribus nostrum ex recusandae laboriosam sint?</h5>
	
	</div>
	
</div>
<div class="row top">
	
	<div class="hidden-xs">
		<img class="img-responsive" id="imgLogistica" src="/img/Servicios/Servicios-logisticos.jpg" usemap="#mapLogistica" alt="" >	
		
		<div id="detalleAduana">
			<div class="detalle-content">
				
					
				<span id="aduanaClose"class="glyphicon glyphicon-remove pull-right icon-close" aria-hidden="true"></span>
				<br>
		    	<h4><strong>TRANSPORTE MARÍTIMO</strong></h4>
				<br>
				Servicios adecuados a las necesidades de cada tipo de carga, cliente y/o negociación de compra-venta.
				<br>
				Atención personalizada 24/7.
				<br>
				Oficinas propias en las principales ciudades de China.
				<br>
				Servicios de Despacho Aduanal en Origen y/o Destino.
				<br>
				Servicio Web Tracking.
				<br>
				Cotizaciones en menos de 24 horas (Puerto-Puerto).
				<br>
				Servicio FCL, LCL, Break Bulk, RoRo, Chartering y Refrigerados.
				<br>
				Proyectos Especiales.
				<br>
				Fletamento de Buques.
			</div>
	  	</div>

	  	<div id="detalleLogistica">
			<div class="detalle-content">
				
					
				<span id="logisticaClose"class="glyphicon glyphicon-remove pull-right icon-close" aria-hidden="true"></span>
				<br>
		    	<h4><strong>TRANSPORTE MARÍTIMO</strong></h4>
				<br>
				Servicios adecuados a las necesidades de cada tipo de carga, cliente y/o negociación de compra-venta.
				<br>
				Atención personalizada 24/7.
				<br>
				Oficinas propias en las principales ciudades de China.
				<br>
				Servicios de Despacho Aduanal en Origen y/o Destino.
				<br>
				Servicio Web Tracking.
				<br>
				Cotizaciones en menos de 24 horas (Puerto-Puerto).
				<br>
				Servicio FCL, LCL, Break Bulk, RoRo, Chartering y Refrigerados.
				<br>
				Proyectos Especiales.
				<br>
				Fletamento de Buques.
			</div>
	  	</div>

		<map name="mapLogistica">

			<area id="btnAduana" 	alt="" shape="rect" coords="0,253,335,335"      />
			<area  					alt="" shape="rect" coords="335,254,667,336"      />
			<area id="btnLogistica"	alt="" shape="rect" coords="666,253,1000,336"     />
			
		</map>	
	</div>
	<div class="hidden visible-xs">
		<img class="img-responsive col-xs-8 col-xs-offset-2 img-rounded" id="imgLogistica " src="/img/Servicios/Movil/logistica1.jpg"  usemap="#logistica1" alt="" />
		<img class="img-responsive col-xs-8 col-xs-offset-2 top img-rounded" id="imgLogistica2" src="/img/Servicios/Movil/logistica2.jpg"  usemap="#logistica2" alt="" />
		<img class="img-responsive col-xs-8 col-xs-offset-2 top img-rounded" id="imgLogistica3" src="/img/Servicios/Movil/logistica3.jpg"  usemap="#logistica3" alt="" />


		<map name="logistica1">
			<area  alt="" title="" href="#1" shape="rect" coords="0,255,334,337"  target="_self"    />
		</map>
		<map name="logistica2">
			<area  alt="" title="" href="#2" shape="rect" coords="0,255,334,337"  target="_self"    />
		</map>
		<map name="logistica3">
			<area  alt="" title="" href="#3" shape="rect" coords="0,255,334,337"  target="_self"    />
		</map>
	</div>
	
</div>

<div class="row top col-xs-10 col-xs-offset-1 justifyText">
	<p class="top">
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus mollis orci, sed rhoncus sapien nunc eget odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus mollis orci, sed rhoncus sapien nunc eget odio.
	</p>
</div>
<div class="page-header col-xs-12"></div>







<script>

	$(document).ready(function(e) {
	    $('img[usemap]').rwdImageMaps();
	});


</script>