<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('ITRADE'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/.ico'))
                        ->prependStylesheet($this->basePath('css/bootstrap.css')) 
                        ->prependStylesheet($this->basePath('css/style.css')) ?>


        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="container">
            <img class="
                        img-responsive 
                        col-lg-3 col-lg-offset-0
                        col-md-3 col-sm-offset-0 
                        col-sm-5 col-sm-offset-0 
                        col-xs-10 col-xs-offset-1
                        " 
            src="img/u38.jpg">
            <a class="
                        bold text-right top
                        col-lg-9 col-lg-offset-0
                        col-md-3 col-sm-offset-0 
                        col-sm-5 col-sm-offset-0 
                        col-xs-10 col-xs-offset-1
                    ">
                <?php echo  $this->translate('Iniciar seción')?>
                
            </a>

        </div>

        <nav class="container navbar navbar-default">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#"></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">              
                <ul class="nav navbar-nav col-lg-6 navbar-right">
                    <li class="col-lg-3"><a class="bRight" href="#"><strong><?php echo  $this->translate('Página 1') ?> </strong></a></li>
                    <li class="col-lg-3"><a class="bRight" href="#"><strong><?php echo  $this->translate('Página 2') ?> </strong></a></li>
                    <li class="col-lg-3"><a class="bRight" href="#"><strong><?php echo  $this->translate('Página 3') ?> </strong></a></li>
                    <li class="col-lg-3"><a class="bRight" href="#"><strong><?php echo  $this->translate('Página 4') ?> </strong></a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->

        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer class="col-lg-6 navbar-right bigTop">        
                
                <li class="col-lg-2 pull-right text-right"><a href="#"><lead><?php echo  $this->translate('Correo') ?> </lead></a></li>
                <li class="col-lg-2 pull-right text-center bRight"><a href="#"><lead><?php echo  $this->translate('Teléfono') ?> </lead></a></li>
                <li class="col-lg-2 pull-right text-center bRight"><a href="#"><lead><?php echo  $this->translate('Ubicación') ?> </lead></a></li>
                <li class="col-lg-2 pull-right text-center bRight"><a href="#"><lead><?php echo  $this->translate('Contacto') ?> </lead></a></li>
                
                <li class="col-lg-12 text-right miniTop"><a href="#"><lead><?php echo  $this->translate('© 2015 ITRADE MEXICO S.A. de C.V.') ?> </lead></a></li>
                
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
