<?php $url="http://".$_SERVER['HTTP_HOST'].":".$_SERVER['SERVER_PORT'].$_SERVER['REQUEST_URI']; ?>
<?php echo $this->doctype(); ?>


<?php
$urlEng = "";
$urlEsp = "";

if (preg_match('/en/',$url))
    $urlEng = $url;
elseif(preg_match('/es/i',$url))
    $urlEng = str_replace("/es","/en",$url); 
else
{
    if(substr($url, -1) != '/')
        $urlEng = $url."/en";
    else
        $urlEng = $url."en";
}

if (preg_match('/es/',$url))
    $urlEsp = $url;
elseif(preg_match('/en/i',$url))
    $urlEsp = str_replace("/en","/es",$url); 
else
{
    if(substr($url, -1) != '/')
        $urlEsp = $url."/es";
    else
        $urlEsp = $url."es";
}


 ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('TEST'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/.ico'))
                        ->prependStylesheet($this->basePath('css/animations.css')) 
                        ->prependStylesheet($this->basePath('css/style.css')) 
                        ->prependStylesheet($this->basePath('css/bootstrap.css'))
                        ->prependStylesheet($this->basePath('css/jasny-bootstrap.css')) 
                        ?>


        <!-- Scripts -->
        <?php echo $this->headScript()
        
            ->prependFile($this->basePath('js/comun.js'))
            ->prependFile($this->basePath('js/bootstrap.js'))
            ->prependFile($this->basePath('js/jasny-bootstrap.js'))
            ->prependFile($this->basePath('js/responsiveMap.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="container" id="tope">
            <a href="http://itrade"><img class="img-responsive col-lg-3 col-lg-offset-0 col-md-3 col-sm-offset-0 col-sm-5 col-sm-offset-0 hidden-xs" src="/img/u38.jpg"></a>

            <div class="bold text-center  col-lg-4 col-lg-offset-5 col-md-4 col-md-offset-5 col-sm-6 col-sm-offset-1 hidden-xs">
                
                <a href="/login"class="col-lg-5 col-lg-offset-3 col-md-5 col-md-offset-2 col-sm-5 col-sm-offset-2">
                    <div class="login"><?php echo  $this->translate('Iniciar sesión')?></div>
                </a>
                
                <div class="col-lg-4 col-md-5 col-sm-5 pull-right">
                    
                    
                    <a href="<?php echo $urlEsp ?>"><img id="" src="/img/español.png" class="imgEsp imgLang " alt=""></a>
                    <a href="<?php echo $urlEng ?>"><img id="" src="/img/inglesH.png" class="imgEng imgLang " alt=""></a>
                
                    
                </div>

            </div>
        </div>

        <a href="<?php echo $urlEsp ?>"><img id="" src="/img/español.png" class="imgEsp imgEsp-xs hidden visible-xs" alt=""></a>
        <a href="<?php echo $urlEng ?>"><img id="" src="/img/inglesH.png" class="imgEng imgEng-xs hidden visible-xs" alt=""></a>


        <nav class="container navbar navbar-default">
          <div class="container col-lg-12">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header  col-xs-3">

              <button type="button" class="navbar-toggle pull-left" data-toggle="offcanvas" data-target="#myNavmenu" data-canvas="body">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#"></a>
            </div>
            <a href="http://itrade"><img src="/img/u38.jpg" class="img-responsive hidden-lg hidden-md hidden-sm col-xs-8 "></a>
            
            <!-- Links del menu movil -->
            <nav id="myNavmenu" class="navmenu navmenu-default navmenu-fixed-left offcanvas " role="navigation">
                <ul class="nav  navmenu">
                    <li><a class="text-center" href="/"><strong><?php echo  $this->translate('Inicio') ?> </strong></a></li>

                    <li><a class="text-center" href="/servicios"><strong><?php echo  $this->translate('Servicios') ?> </strong></a></li>
                    <li class=" dropdown text-center">
                        <a href="#" class="dropdown-toggle bRight" data-toggle="dropdown" data-hover="dropdown" data-delay="" data-close-others="false">
                            <strong><?php echo  $this->translate('Recursos') ?></strong> <b class="caret"></b>
                        </a>
                        

                        <ul class="dropdown-menu blue navmenu-nav " >
                            <li><a class="text-center"href="#"><?php echo  $this->translate('PDF')?></a></li>
                            <li class="divider"></li>
                            <li><a class="text-center"href="#"><?php echo  $this->translate('PDF')?></a></li>
                        </ul>
                    </li>
                    <li><a class="text-center" href="/contacto"><strong><?php echo  $this->translate('Contacto') ?> </strong></a></li>
                    <li><a href="login"class="text-center">
                    
                </a></li>
                </ul>
            </nav>

            <div class="collapse navbar-collapse " id="bs-example-navbar-collapse-1 ">              
                <ul class="nav navbar-nav  navbar-right ">
                    <li id="navInicio"class=""><a class="bRight specialAlign" href="/"><strong><?php echo  $this->translate('Inicio') ?> </strong></a></li>
                    <li id="navServicios"class=""><a class="bRight specialAlign" href="/servicios"><strong><?php echo  $this->translate('Servicios') ?> </strong></a></li>

                    <li id="navRecursos" class=" dropdown">
                        <a href="#" class="dropdown-toggle bRight" data-toggle="dropdown" data-hover="dropdown" data-delay="" data-close-others="false">
                            <strong><?php echo  $this->translate('Recursos') ?></strong> <b class="caret"></b>
                        </a>
                        

                        <ul class="dropdown-menu blue " >
                            <li><a class="textWhite"href="#"><?php echo  $this->translate('PDF')?></a></li>
                            <li class="divider"></li>
                            <li><a href="#">PDF</a></li>
                        </ul>
                    </li>

                    
                    <li id="navContacto" class=""><a class=" specialAlign" href="/contacto"><strong><?php echo  $this->translate('Contacto') ?> </strong></a></li>
                </ul>
            </div>
          </div>

        </nav>
        <div class="container">
            <a href="/contacto/maritimo"class="btn-cotizar btn hidden-xs"><img src="/img/cotizar.png" class="img-responsive img-rounded"></a>
            <a href="/contacto/maritimo"class="btn-cotizar-xs hiddev visible-xs"><span class="glyphicon glyphicon-usd"></span> <?php echo  $this->translate('COTIZAR')?></a>

            <a href="/login"class="btn-user-xs hiddev visible-xs"><span class="glyphicon glyphicon-user"></span> </a>

            <a class="btn-up-xs hiddev visible-xs"><span class="glyphicon glyphicon-menu-up"></span> </a>
            <?php echo $this->content; ?>
            
            <footer class="col-lg-6 col-lg-offset-6  top">        
                
                
                
                <li class="col-lg-12 col-xs-12 text-right">
                    <a href="#"><lead><?php echo  $this->translate('© 2015 ITRADE MEXICO S.A. de C.V.') ?> </lead></a>
                </li>
                <li class="col-lg-12 col-xs-12 text-right">
                    <a target="_blank"href="https://goo.gl/maps/Ypx3yduiYVK2"><lead class="textBlue"><?php echo  $this->translate('San Antonio de Padua #740-A. Camino Real, Zapopan, Jalisco C.P. 45040') ?> </lead></a>
                </li>
                <li class="col-lg-12 col-xs-12 text-right">
                    <a href="mailto:luis.contreras@itrade.com.mx" ><lead class="textBlue"><?php echo  $this->translate('luis.contreras@itrade.com.mx') ?> </lead></a>
                    <lead><?php echo  $this->translate(' Oficina: +52(33)20010565')?></lead>
                </li>
                
                <a href="https://www.instagram.com/itrademexico/" target="_blank"><img src="/img/footer/linked.png" class="pull-right social-ico" alt=""></a>
                <a href="https://twitter.com/ITradeMexico" target="_blank"><img src="/img/footer/twitter.png" class="pull-right social-ico" alt=""></a>
                <a href="https://www.facebook.com/Itrade-Mexico-632336230208434/?fref=ts" target="_blank"><img src="/img/footer/facebook.png" class="pull-right social-ico" alt=""></a>
                <br> <br> 
            </footer>
        </div> <!-- /container -->
        <script src="/js/layout/layout.js"></script>
        <script>
        $( ".btn-up-xs" ).click(function() {
            $('html,body').animate({
                scrollTop: $("#tope").offset().top
            }, 1000);
        });
        </script>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
