<div class="form_container">
    
    <ul class="breadcrumb">
        <li>
            <p>Catalogo</p>
        </li>
        <li>
            <a href="javascript:;">Gastos facturación</a>
        </li>
        <li>
            <a href="/catalogo/categorias-gastos">Categorias</a>
        </li>
        <li>
            <a class="active" href="/catalogo/categorias-gastos/editar/<?php echo $form->get('idcategoriagasto')->getValue()?>"><?php echo $form->get('categoriagasto_nombre')->getValue()?></a>
        </li>
    </ul>
    <div class="page-title">
        <h3><span class="semi-bold"><?php echo strtoupper($form->get('categoriagasto_nombre')->getValue())?></span></h3>
    </div>
    <?php 
        $form->setAttribute('action', '/catalogo/categorias-gastos/editar/'.$form->get('idcategoriagasto')->getValue());
        $form->setAttribute('novalidate', true);
        $form->setAttribute('enctype', 'multipart/form-data');

        echo $this->form()->openTag($form); 
    ?>
    <div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4><span class="semi-bold">Información general</span></h4>
                    <div class="tools">
                        <a class="collapse" href="javascript:;"></a>
                    </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('categoriagasto_nombre')) ?>  
                                    <span class="help req">*</span>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('categoriagasto_nombre')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('categoriagasto_descripcion')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formTextarea($form->get('categoriagasto_descripcion')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="pull-right">
                        <button btn_action="submit" class="btn btn-primary btn-cons" type="button">Guardar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php 
        echo $this->form()->closeTag(); 
    ?>
</div>
<!--CUSTOM SCRIPT-->
<script src="/js/admin/catalogo/categoriagastos.js"></script>

<script type="text/javascript">
    
    $(document).ready(function() {
        //FORM BIND
        var $form = $('.form_container').categoriagastos({successMessages:<?php echo $successMessages?>});
        $form.formBind(true,<?php echo $entity?>);

    });
</script>


