<?php if ($_POST): ?>
	
	<?php

	$nombre 	= $_POST['nombre'];
	$empresa 	= $_POST['empresa'];
	$email 		= $_POST['email'];
	$telefono 	= $_POST['telefono'];
	$mensaje 	= $_POST['mensaje'];

	$bodyMessage = 'Nombre: '.$nombre.'<br>Empresa: '.$empresa.'<br>Email: '.$email.'<br>Telefono: '.$telefono.'<br>Mensaje: '.$mensaje.'<br><br> Ponte en contacto con el';

	require 'PHPMailer/PHPMailerAutoload.php';

	$mail = new PHPMailer;


	$mail->isSMTP();                                      // Set mailer to use SMTP
	$mail->Host = 'smtp.gmail.com server';  // Specify main and backup SMTP servers
	$mail->SMTPAuth = true;                               // Enable SMTP authentication
	$mail->Password = '********';                           // SMTP password
	$mail->Username = 'mail@server.com';                 // SMTP username
	$mail->SMTPSecure = 'ssl';                            // Enable TLS encryption, `ssl` also accepted
	$mail->Port = 465;                                    // TCP port to connect to

	$mail->setFrom($email, 'ITRADE Contacto');
	$mail->addAddress('mailtorecipe@server.com', $nombre);     // Add a recipient

	$mail->isHTML(true);                                  // Set email format to HTML

	$mail->Subject = 'Ponte en contacto WEB';
	$mail->Body    = $bodyMessage;
	//	$mail->AltBody = '';

	if(!$mail->send()) 
	{?>
	    <div class="alert alert-danger" role="alert">Lo siento '.$nombre.' no pudimos enviar el correo </div>
    <?php 
	} else 
	{?>
		<div class="alert alert-success" role="alert">Muchas gracias <?php echo $nombre ?> por enviar tus datos, nos pondremos en contacto a la brevedad .... </div>
   	<?php 
	}

	?>

<?php endif ?>

<div class="row specialAlign">
	
	<div class="page-header"></div>
	<h3 class="bold">Contacto</h3>
	
	<div class="bold top">Tienes dudas acerca de algún trámite con nosotros?</div>
 
	<div class="bold miniTop">Necesitas informes de algún servicio que ofrecemos?</div>
 
	<div class="bold miniTop">Estamos aquí para ayudar y puedes contactarnos de varias maneras! </div>
	
	<div class="top">Estamos disponibles en los siguientes horarios:</div>
 	
 	<div class="top">
		Lun - Vier: 9:00am - 6:00pm <br>
		Sábados: 9:00am - 2:00pm
	</div>

	<div class="page-header"></div>

	<div class="bold top">Contacta a nuestro equipo de soporte via email:</div>

	<div class="top">Para ventas: ventas@itrademexico.com.mx</div>
 
	Para soporte: soporte@itrademexico.com.mx
	<div class="page-header"></div>

	<div class="top bold">Llámanos!</div>
 	<div class="top">
		<strong>Servicio al Cliente:</strong> <lead>+52(33)20010565</lead>
 	</div>

	<div class="miniTop"><strong>Soporte Logístico:</strong> +52(33)20010566</div>

</div>
<div class="top"></div>
<div class=" row  top blue">
	<div class="col-lg-4 col-xs-12 col-sm-12 col-md-4">
		<h2 class="textWhite specialAlign">Lorem ipsum dolor sit amet, consectetur </h2>
		<h4 class="textWhite specialAlign top"> adipisicing elit </h4>
	</div>
	<div class="col-lg-8 col-xs-12 col-sm-12 col-md-8 bot">

		<form class="textWhite" action="/contacto" method="post">

			<div class="form-group row miniTop">
				<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12 formAlign">
					<label for="nombre">Nombre: *</label>
				</div>
				<div class="col-lg-8 col-md-8  col-sm-8 col-xs-12">
					<input type="text" class="form-control" id="nombre" name="nombre" required>
				</div>
			</div>

			<div class="form-group row">
				<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12 formAlign">
					<label for="empresa">Empresa:</label>
				</div>
				<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
					<input type="text" class="form-control" id="empresa" name="empresa" >
				</div>
			</div>
			
			<div class="form-group row">
				<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12 formAlign">
					<label for="email">Dirección de e-mail: *</label>
				</div>
				<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
					<input type="text" class="form-control" id="email" name="email" required>
				</div>
			</div>

			<div class="form-group row">
				<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12 formAlign">
					<label for="telefono">Teléfono/Fax: *</label>
				</div>
				<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
					<input type="text" class="form-control" id="telefono" name="telefono" required>
				</div>
			</div>

			<div class="form-group row">
				<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12 formAlign">
					<label for="mensaje">Mensaje: *</label>
				</div>
				<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
					<textarea name="mensaje" id="mensaje" class="form-control" rows="3" required></textarea>
				</div>
			</div>


			<div class="form-group  row">
				<div class="col-lg-3 col-lg-offset-9 col-md-3 col-md-offset-9 col-xs-6 col-xs-offset-3">
					<button class="btn btn-danger form-control  ">Acción</button>
				</div>
			</div>



				 
			
		  
		</form>
	</div>
		
</div>