<div class="row specialAlign">
	
	<div class="page-header"></div>
	<h3 class="bold">Contacto</h3>
	
	<div class="bold top">Tienes dudas acerca de algún trámite con nosotros?</div>
 
	<div class="bold miniTop">Necesitas informes de algún servicio que ofrecemos?</div>
 
	<div class="bold miniTop">Estamos aquí para ayudar y puedes contactarnos de varias maneras! </div>
	
	<div class="top">Estamos disponibles en los siguientes horarios:</div>
 	
 	<div class="top">
		Lun - Vier: 9:00am - 6:00pm <br>
		Sábados: 9:00am - 2:00pm
	</div>

	<div class="page-header"></div>

	<div class="bold top">Contacta a nuestro equipo de soporte via email:</div>

	<div class="top">Para ventas: ventas@itrademexico.com.mx</div>
 
	Para soporte: soporte@itrademexico.com.mx
	<div class="page-header"></div>

	<div class="top bold">Llámanos!</div>
 	<div class="top">
		<strong>Servicio al Cliente:</strong> <lead>+52(33)20010565</lead>
 	</div>

	<div class="miniTop"><strong>Soporte Logístico:</strong> +52(33)20010566</div>

</div>
<div class="top"></div>
<div class=" row  top blue">
	<div class="col-lg-6 col-xs-12 col-sm-12 col-md-6">
		<h2 class="textWhite specialAlign">Lorem ipsum dolor sit amet, consectetur </h2>
		<h4 class="textWhite specialAlign top"> adipisicing elit </h4>
	</div>
	<div class="col-lg-5 col-xs-12 col-sm-12 col-md-6 bot">
		<form class="textWhite ">
			<div class="row">

				<div class="col-lg-2  col-xs-2  col-sm-2 col-md-2 text-right"><label for="exampleInputEmail1">Texto</label></div>
				<div class="col-lg-10 col-xs-10"><input type="text" class="form-control" id="exampleInputEmail1" placeholder="placeHolder"></div>
			
				<div class="col-lg-2  col-xs-2  col-sm-2 col-md-2 text-right miniTop"><label for="exampleInputEmail1">Texto</label></div>
				<div class="col-lg-10 col-xs-10 miniTop"><input type="text" class="form-control" id="exampleInputEmail1" placeholder="placeHolder"></div>
			
				<div class="col-lg-2  col-xs-2  col-sm-2 col-md-2 text-right miniTop"><label for="exampleInputEmail1">Texto</label></div>
				<div class="col-lg-10 col-xs-10 miniTop"><input type="text" class="form-control" id="exampleInputEmail1" placeholder="placeHolder"></div>
			
				<div class="col-lg-12 col-xs-12 miniTop">
					<button class="btn btn-danger col-lg-3 col-lg-offset-9 col-xs-6 col-xs-offset-3 col-md-6 col-md-offset-6">Acción</button>
				</div>
				 
			
			</div>
		  
		</form>
	</div>
		
</div>