<?php if ($_POST): ?>
	
	<?php

	$nombre 	= $_POST['nombre'];
	$empresa 	= $_POST['empresa'];
	$email 		= $_POST['email'];
	$telefono 	= $_POST['telefono'];
	$mensaje 	= $_POST['mensaje'];
	$servicio   = $_POST['servicio'];

	$bodyMessage = 'Nombre: '.$nombre.'<br>Empresa: '.$empresa.'<br>Email: '.$email.'<br>Telefono: '.$telefono.'<br>Mensaje: '.$mensaje.'<br><br> Ponte en contacto con el<br>Tipo de servicio: '.$servicio;

	require 'PHPMailer/PHPMailerAutoload.php';

	$mail = new PHPMailer;


	$mail->isSMTP();                                      	// Set mailer to use SMTP
	$mail->Host = 'smtp.gmail.com server';  				// Specify main and backup SMTP servers
	$mail->SMTPAuth = true;                               	// Enable SMTP authentication
	$mail->Password = '********';                           // SMTP password
	$mail->Username = 'mail@server.com';                 	// SMTP username
	$mail->SMTPSecure = 'ssl';                            	// Enable TLS encryption, `ssl` also accepted
	$mail->Port = 465;                                    	// TCP port to connect to

	$mail->setFrom($email, 'ITRADE Contacto');
	$mail->addAddress('mailtorecipe@server.com', $nombre);  // Add a recipient

	$mail->isHTML(true);                                  	// Set email format to HTML

	$mail->Subject = 'Ponte en contacto WEB';
	$mail->Body    = $bodyMessage;
	//	$mail->AltBody = '';

	if(!$mail->send()) 
	{?>
	    <div class="alert alert-danger" role="alert">Lo siento '.$nombre.' no pudimos enviar el correo </div>
    <?php 
	} else 
	{?>
		<div class="alert alert-success" role="alert">Muchas gracias <?php echo $nombre ?> por enviar tus datos, nos pondremos en contacto a la brevedad .... </div>
   	<?php 
	}

	?>

<?php endif ?>

<?php if ($servicio != null): ?>
	
	<script>
		$( document ).ready(function() {
	    $('html,body').animate({
	        scrollTop: $("#contacto").offset().top
	    }, 2000);
	});
	</script>

<?php endif ?>



<div class="row specialAlign">
	
	<div class="page-header"></div>
	<h3 class="bold"><?php echo  $this->translate('Contacto')?></h3>
	
	<div class="bold top"><?php echo  $this->translate('Acércate a nosotros, será un gusto apoyarte!')?></div>
 <!--
	<div class="bold miniTop"><?php echo  $this->translate('Necesitas informes de algún servicio que ofrecemos?')?></div>
 
	<div class="bold miniTop"><?php echo  $this->translate('Estamos aquí para ayudar y puedes contactarnos de varias maneras!')?> </div>
	
	<div class="top"><?php echo  $this->translate('Estamos disponibles en los siguientes horarios:')?></div>
 	
 	<div class="top">
 		<?php echo  $this->translate('
		Lun - Vier: 9:00am - 6:00pm <br>
		Sábados: 9:00am - 2:00pm
		')?>
	</div>
-->
	<div class="page-header"></div>

	<div class="bold top"><?php echo  $this->translate('Contacta a nuestro equipo de soporte via email')?>:</div>

	<div class="top">
		<?php echo  $this->translate('General Manager<br>Luis Contreras<br>')?>
		<a href="mailto:luis.cotreras@itrademexico.com.mx" class="textBlue">luis.cotreras@itrademexico.com.mx</a>
	</div>
	
 	
	<?php echo  $this->translate('<br>Sales Manager<br>Ninfa Ortiz<br>')?>
	<a href="mailto:ninfa.ortiz@itrademexico.com.mx" class="textBlue">ninfa.ortiz@itrademexico.com.mx</a>
	<?php echo  $this->translate('<br><br>Operations Manager<br>Erick Martinez<br>')?>
	<a href="mailto:erick.martinez@itrademexico.com.mx" class="textBlue">erick.martinez@itrademexico.com.mx</a>

	

	
</div>
<div class="top"></div>

<div class="row">

	<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d29865.33909276099!2d-103.415192!3d20.662768!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8428ae8317cb4c77%3A0xc1fd5bcf250bf64d!2sSan+Antonio+de+Padua+740%2C+Camino+Real%2C+45040+Zapopan%2C+Jal.%2C+M%C3%A9xico!5e0!3m2!1ses!2smx!4v1449204564133" width="100%" height="250" frameborder="0" style="border:0" allowfullscreen></iframe>
	
	<div class="italic">San Antonio de Padua #740-A. Camino Real, Zapopan, Jalisco C.P. 45040</div><br>
</div>

<div class="page-header"></div>

	<div class="top bold"><?php echo  $this->translate('Llámanos!')?></div>
 	<div class="top">
		<strong><?php echo  $this->translate('Servicio al Cliente:')?></strong> <lead>+52(33)20010565</lead>
 	</div>

<div class="miniTop"><strong><?php echo  $this->translate('Soporte Logístico:')?></strong> +52(33)20010566</div>
<br>

<div id="contacto" class="  row top blue">
	<div class="col-lg-4 col-xs-12 col-sm-12 col-md-4">
		<h1 class="textWhite specialAlign"><?php echo  $this->translate('Contactanos')?></h1>
		<h3 class="textWhite specialAlign"><?php echo  $this->translate('Nosotros podemos ayudarte.')?> </h3>
	</div>
	<div class="col-lg-8 col-xs-12 col-sm-12 col-md-8 bot ">
		<form class="textWhite" action="http://itrade" method="post">

			<div class="form-group  row">
				<div class="col-lg-4 col-lg-offset-0 col-md-4 col-sm-3 col-xs-12 formAlign ">
					<label for="nombre"><?php echo  $this->translate('Nombre')?>: *</label>
				</div>
				<div class="col-lg-8 col-md-8  col-sm-8 col-xs-12">
					<input type="text" class="form-control" id="nombre" name="nombre" required>
				</div>
			</div>

			<div class="form-group row">
				<div class="col-lg-4 col-lg-offset-0 col-md-4 col-sm-3 col-xs-12 formAlign ">
					<label for="empresa"><?php echo  $this->translate('Empresa')?>:</label>
				</div>
				<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
					<input type="text" class="form-control" id="empresa" name="empresa" >
				</div>
			</div>
			
			<div class="form-group row ">
				<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12 formAlign ">
					<label for="email"><?php echo  $this->translate('Dirección de e-mail')?>: *</label>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-8 col-xs-12">
					<input type="text" class="form-control" id="email" name="email" required>
				</div>
				<div class="col-lg-2 col-md-2 col-sm-3 col-xs-12 formAlign top-sm ">
					<label for="telefono"><?php echo  $this->translate('Teléfono')?>: *</label>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-8 col-xs-12 top-sm">
					<input type="text" class="form-control" id="telefono" name="telefono" required>
				</div>
			</div>


			<div class="form-group row">
				<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12 formAlign ">
					<label for="mensaje"><?php echo  $this->translate('Mensaje')?>: *</label>
				</div>
				<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
					<textarea name="mensaje" id="mensaje" class="form-control" rows="3" required></textarea>
				</div>
			</div>

			<div class="form-group row">
				<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12 formAlign ">
					<label for="mensaje"><?php echo  $this->translate('Tipo de servicio')?>: *</label>
				</div>
				<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
					
					<select name="cbServicio" id="cbServicio" class="form-control">
						<?php if ($servicio == 'maritimo'): ?>
							<option selected value="maritimo"><?php echo  $this->translate('Marítimo')?></option>
						<?php else: ?>
							<option value="maritimo"><?php echo  $this->translate('Marítimo')?></option>
						<?php endif ?>
						<?php if ($servicio == 'aereo'): ?>
							<option value="aereo" selected><?php echo  $this->translate('Aereo')?></option>
						<?php else: ?>
							<option value="aereo"><?php echo  $this->translate('Aereo')?></option>
						<?php endif ?>
						<?php if ($servicio == 'terrestre'): ?>
							<option selected value="terrestre"><?php echo  $this->translate('Terrestre')?></option>
						<?php else: ?>
							<option value="terrestre"><?php echo  $this->translate('Terrestre')?></option>
						<?php endif ?>
						<?php if ($servicio == 'aduana'): ?>
							<option selected value="aduana"><?php echo  $this->translate('Aduana')?></option>
						<?php else: ?>
							<option value="aduana"><?php echo  $this->translate('Aduana')?></option>
						<?php endif ?>
						<?php if ($servicio == 'seguro'): ?>
							<option selected value="seguro"><?php echo  $this->translate('Seguro')?></option>
						<?php else: ?>
							<option value="seguro"><?php echo  $this->translate('Seguro')?></option>
						<?php endif ?>
					</select>
				</div>
			</div>


			<div class="form-group row">
				<div class="col-lg-3 col-lg-offset-9 col-md-3 col-md-offset-9 col-sm-4 col-sm-offset-5 col-xs-6 col-xs-offset-3 top">
					<button class="btn btn-danger  col-lg-12 col-md-10 col-sm-12 col-xs-12 "><?php echo  $this->translate('Enviar')?></button>
				</div>
			</div>
			<div class="row"></div> 

		</form>
	</div>
		
</div>

