<div class="empleado_form_container">
    
    <ul class="breadcrumb">
        <li>
            <p>Catalogo</p>
        </li>
        <li>
            <a href="/catalogo/empleados">Empleados</a>
        </li>
        <li>
            <a class="active" href="/catalogo/empleados/editar/<?php echo $form->get('idempleado')->getValue()?>"><?php echo $form->get('empleado_nombre')->getValue().' '.$form->get('empleado_apellidopaterno')->getValue().' '.$form->get('empleado_apallidomaterno')->getValue()?></a>
        </li>
    </ul>
    <div class="page-title">
        <h3><span class="semi-bold"><?php echo strtoupper($form->get('empleado_nombre')->getValue().' '.$form->get('empleado_apellidopaterno')->getValue().' '.$form->get('empleado_apallidomaterno')->getValue())?></span></h3>
    </div>
    <?php 
        $form->setAttribute('action', '/catalogo/empleados/editar/'.$form->get('idempleado')->getValue());
        $form->setAttribute('novalidate', true);
        $form->setAttribute('enctype', 'multipart/form-data');

        echo $this->form()->openTag($form); 
    ?>
    <div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4><span class="semi-bold">Información general</span></h4>
                    <div class="tools">
                        <a class="collapse" href="javascript:;"></a>
                    </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('empleado_nombre')) ?>  
                                    <span class="help req">*</span>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('empleado_nombre')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('empleado_apellidopaterno')) ?>  
                                    <span class="help req">*</span>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('empleado_apellidopaterno')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('empleado_apallidomaterno')) ?>  
                                    <span class="help req">*</span>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('empleado_apallidomaterno')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('empleado_celular')) ?>  
                                    <span class="help req">*</span>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('empleado_celular')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('empleado_telefono')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('empleado_telefono')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('empleado_calle')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('empleado_calle')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('empleado_numero')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('empleado_numero')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('empleado_interior')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('empleado_interior')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('empleado_colonia')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('empleado_colonia')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('empleado_codigopostal')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('empleado_codigopostal')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('empleado_ciudad')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('empleado_ciudad')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('empleado_estado')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formSelect($form->get('empleado_estado')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4><span class="semi-bold">Información laboral</span></h4>
                    <div class="tools">
                        <a class="collapse" href="javascript:;"></a>
                    </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('empleado_rfc')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('empleado_rfc')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('empleado_nss')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('empleado_nss')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('empleado_iniciocontrato')) ?>  
                                    <div class="controls">
                                        <div class="input-with-icon  right">
                                            <div class="input-append success date width-93">
                                                <i class=""></i>
                                                <?php echo $this->formText($form->get('empleado_iniciocontrato')) ?>  
                                                <span class="add-on"><span class="arrow"></span><i class="fa fa-th"></i></span> 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4><span class="semi-bold">Información de contacto</span></h4>
                    <div class="tools">
                        <a class="collapse" href="javascript:;"></a>
                    </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('empleado_nombrecontacto')) ?>  

                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('empleado_nombrecontacto')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('empleado_telefonocontacto')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('empleado_telefonocontacto')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4><span class="semi-bold">Datos de acceso</span></h4>
                    <div class="tools">
                        <a class="collapse" href="javascript:;"></a>
                    </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <div class="row-fluid">
                                    <div class="form-group">
                                        <?php echo $this->formLabel($form->get('empleado_rol')) ?>  
                                        <span class="help req">*</span>
                                        <div class="input-with-icon right ">
                                            <i class=""></i>
                                            <?php echo $this->formSelect($form->get('empleado_rol')) ?>  
                                        </div>
                                        <span class="error"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <div class="row-fluid">
                                    <div class="form-group">
                                        <?php echo $this->formLabel($form->get('empleado_email')) ?>  
                                        <span class="help req">*</span>
                                        <div class="input-with-icon  right">
                                            <i class=""></i>
                                            <?php echo $this->formText($form->get('empleado_email')) ?>  
                                        </div>
                                        <span class="error"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <div class="row-fluid">
                                    <div class="form-group">
                                        <?php echo $this->formLabel($form->get('empleado_estatus')) ?>  
                                        <span class="help req">*</span>
                                        <div class="input-with-icon right ">
                                            <i class=""></i>
                                            <?php echo $this->formSelect($form->get('empleado_estatus')) ?>  
                                        </div>
                                        <span class="error"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4><span class="semi-bold">Fotografia</span></h4>
                    <div class="tools">
                        <a class="collapse" href="javascript:;"></a>
                    </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row">
                        <div style="text-align: center" class="col-md-4 col-sm-4 col-xs-4 col-xs-push-4 col-md-push-4 col-sm-push-4">
                             <?php echo $this->formFile($form->get('empleado_foto')) ?>
                             <img class="empleado_foto" style="width: 233px; height: 232px;"id="image" src="/img/admin/profiles/avatar_default.jpg">
                            <p id="eliminar_imagen" style="text-align: center; display: none"><a style="text-decoration: none" href="javascript:void(0)">Eliminar Imagen</a></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="pull-right">
                        <button btn_action="submit" class="btn btn-primary btn-cons" type="button">Guardar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php 
        echo $this->form()->closeTag(); 
    ?>
</div>
<!--IMPORTAMOS SCRIPTS DE CROPPER-->
<link rel="stylesheet" href="/plugins/admin/cropper/cropper.css">
<script src="/plugins/admin/cropper/cropper.js"></script>
<!--CUSTOM SCRIPT-->
<script src="/js/admin/catalogo/empleados.js"></script>

<script type="text/javascript">
    
    $(document).ready(function() {
        //FORM BIND
        var $form = $('.empleado_form_container').empleados({successMessages:<?php echo $successMessages?>});
        $form.formBind(true,<?php echo $entity?>);

    });
</script>
