<div class="list_container">
    <ul class="breadcrumb">
        <li>
            <p>Catalogo</p>
        </li>
        <li>
            <a class="active" href="/catalogo/empleados">Empleados</a>
        </li>
    </ul>
    <div class="page-title">
        <h3><span class="semi-bold">EMPLEADOS</span></h3>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-title no-border">
                    <div class="tools">
                        <!--<a href="#" data-toggle="dropdown" class="btn dropdown-toggle btn-demo-space"> Default <span class="caret"></span> </a>-->
                        <!--<a data-toggle="dropdown" href="javascript:void(0)" class="config dropdown-menu-left"></a>-->
                        
                        <div class="btn-group"> <a href="#" data-toggle="dropdown" class="btn dropdown-toggle btn-demo-space"> Default <span class="caret"></span> </a>
                            <ul class="dropdown-menu dropdown-menu-left">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </div>

                    </div>
                    <br>
                </div>
                <div class="grid-body no-border">
                    <table id="example" class="table">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Correo electrónico</th>
                                <th>Celular</th>
                                <th>Rol</th>
                                <th>Opciones</th>
                            </tr>
                    </thead>
                    <tbody>
                        
                    </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!--CUSTOM SCRIPT-->
<script src="/js/admin/catalogo/empleados.js"></script>
<script>
    $(document).ready(function() {
        var empleados = $('.list_container').empleados({successMessages:<?php echo $successMessages?>});
        empleados.list();
    }); 
</script>

