<?php if ($_POST): ?>
	
	<?php

	$nombre 	= $_POST['nombre'];
	$empresa 	= $_POST['empresa'];
	$email 		= $_POST['email'];
	$telefono 	= $_POST['telefono'];
	$mensaje 	= $_POST['mensaje'];

	$bodyMessage = 'Nombre: '.$nombre.'<br>Empresa: '.$empresa.'<br>Email: '.$email.'<br>Telefono: '.$telefono.'<br>Mensaje: '.$mensaje.'<br><br> Ponte en contacto con el';

	require 'PHPMailer/PHPMailerAutoload.php';

	$mail = new PHPMailer;


	$mail->isSMTP();                                      // Set mailer to use SMTP
	$mail->Host = 'smtp.gmail.com server';  // Specify main and backup SMTP servers
	$mail->SMTPAuth = true;                               // Enable SMTP authentication
	$mail->Password = '********';                           // SMTP password
	$mail->Username = 'mail@server.com';                 // SMTP username
	$mail->SMTPSecure = 'ssl';                            // Enable TLS encryption, `ssl` also accepted
	$mail->Port = 465;                                    // TCP port to connect to

	$mail->setFrom($email, 'ITRADE Contacto');
	$mail->addAddress('mailtorecipe@server.com', $nombre);     // Add a recipient

	$mail->isHTML(true);                                  // Set email format to HTML

	$mail->Subject = 'Ponte en contacto WEB';
	$mail->Body    = $bodyMessage;
	//	$mail->AltBody = '';

	if(!$mail->send()) 
	{?>
	    <div class="alert alert-danger" role="alert">Lo siento '.$nombre.' no pudimos enviar el correo </div>
    <?php 
	} else 
	{?>
		<div class="alert alert-success" role="alert">Muchas gracias <?php echo $nombre ?> por enviar tus datos, nos pondremos en contacto a la brevedad .... </div>
   	<?php 
	}

	?>

<?php endif ?>


<div class="row">
	<div id="mainCarousel" class="carousel slide col-lg-12 col-md-12 col-sm-12 col-xs-12" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
		<li data-target="#mainCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#mainCarousel" data-slide-to="1"></li>
		<li data-target="#mainCarousel" data-slide-to="2"></li>
		</ol>

		<!-- Wrapper for slides -->
		<div class="carousel-inner" role="listbox">
			<div class="item active">
			  <img src="img/u2.jpg" alt="...">
			  <div class="carousel-caption text-left row hidden-xs hidden-sm">
				<h2 id="textCar1">BRINDAMOS SOLUCIONES LOGÍSTICAS Y ADUANALES PARA TU NEGOCIO</h2>
			  </div>
			</div>
			<div class="item">
			  <img src="img/u2.jpg" alt="...">
			  <div class="carousel-caption">
			    
			  </div>
			</div>
			<div class="item">
			  <img src="img/u2.jpg" alt="...">
			  <div class="carousel-caption">
			    
			  </div>
			</div>
		</div>

		<!-- Controls -->
		<a class="left carousel-control" href="#mainCarousel" role="button" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="right carousel-control" href="#mainCarousel" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>

	<div class="col-lg-6 col-lg-offset-0 col-xs-12 col-xs-offset-0 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-0 bigTop">
		<img src="img/u71.jpg" class="img-responsive">
	</div>
	
	<div class="col-lg-6 col-lg-offset-0 col-xs-12 col-xs-offset-0 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-0 top">

		<small class="specialAlign col-xs-12 col-sm-12 ">
		<h3 class="bold specialAlign">Bienvenido a ITRADE México</h3>
		ITRADE es una compañía joven especializada en intercambios y gestión de negocios y contactos comerciales en todos los campos del transporte y la logística
		de mercancías.﻿
 		<br><br>
		Rapidez, eficiencia y seguridad son determinantes en el ramo transportista, ITRADE además de cubrir estos aspectos le ofrece un excelente servicio a un inmejorable precio. Nuestros servicios de logística y transporte están creados para safisfacer sus requerimientos con gran calidad. Conozca más sobre los sevicios que le ofrecemos.
		</small>
	</div>

	<div class="page-header col-lg-12 col-xs-12 col-sm-12 col-md-12"></div>

	<div class="col-lg-6 col-lg-offset-0 col-xs-12 col-xs-offset-0 col-sm-12  col-md-6 col-md-offset-0 top">
		<img src="img/u73.jpg" class="img-responsive col-lg-6 col-lg-offset-0 col-xs-12 col-xs-offset-0 col-sm-6 col-sm-offset-0 col-md-6 col-md-offset-0">
		<img src="img/u75.png" class="img-responsive col-lg-6 col-lg-offset-0 col-xs-12 col-xs-offset-0 col-sm-6 col-sm-offset-0 col-md-6 col-md-offset-0">
	</div>
	<div class="col-lg-6 col-lg-offset-0 col-xs-12 col-xs-offset-0 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-0 ">
		<h3 class="bold specialAlign">Lorem ipsum dolor sit amet, consectetur adipisicing elit</h3>
		<small class="specialAlign col-xs-12">sed do eiusmod hola mundo
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		</small>
	</div>
</div>

<div class="top"></div>

<div class=" row  top blue">
	<div class="col-lg-4 col-xs-12 col-sm-12 col-md-4">
		<h2 class="textWhite specialAlign">Lorem ipsum dolor sit amet, consectetur </h2>
		<h4 class="textWhite specialAlign top"> adipisicing elit </h4>
	</div>
	<div class="col-lg-8 col-xs-12 col-sm-12 col-md-8 bot">
		<form class="textWhite" action="http://itrade" method="post">

			<div class="form-group row miniTop">
				<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12 formAlign">
					<label for="nombre">Nombre: *</label>
				</div>
				<div class="col-lg-8 col-md-8  col-sm-8 col-xs-12">
					<input type="text" class="form-control" id="nombre" name="nombre" required>
				</div>
			</div>

			<div class="form-group row">
				<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12 formAlign">
					<label for="empresa">Empresa:</label>
				</div>
				<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
					<input type="text" class="form-control" id="empresa" name="empresa" >
				</div>
			</div>
			
			<div class="form-group row">
				<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12 formAlign">
					<label for="email">Dirección de e-mail: *</label>
				</div>
				<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
					<input type="text" class="form-control" id="email" name="email" required>
				</div>
			</div>

			<div class="form-group row">
				<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12 formAlign">
					<label for="telefono">Teléfono/Fax: *</label>
				</div>
				<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
					<input type="text" class="form-control" id="telefono" name="telefono" required>
				</div>
			</div>

			<div class="form-group row">
				<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12 formAlign">
					<label for="mensaje">Mensaje: *</label>
				</div>
				<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
					<textarea name="mensaje" id="mensaje" class="form-control" rows="3" required></textarea>
				</div>
			</div>


			<div class="form-group  row">
				<div class="col-lg-3 col-lg-offset-9 col-md-3 col-md-offset-9 col-xs-6 col-xs-offset-3">
					<button class="btn btn-danger form-control  ">Acción</button>
				</div>
			</div>



				 
			
		  
		</form>
	</div>
		
</div>

<div class="row">
	<div class="col-lg-12 col-xs-12 col-sm-12 col-md-12 bigTop specialAlign">
		Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	</div>
	<div class="page-header col-lg-12 col-xs-12 col-sm-12 col-md-12"></div>
</div>


<script>
$( document ).ready(function() 
{
	//Animacion de carousel
	$('#textCar1').addClass('magictime spaceInLeft');
});

	
</script>