<h1><?php //echo $this->translate('Bienvenido')?></h1>


<div class="row">
	<div id="mainCarousel" class="carousel slide col-lg-12 col-md-12 col-sm-12 col-xs-12" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
		<li data-target="#mainCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#mainCarousel" data-slide-to="1"></li>
		<li data-target="#mainCarousel" data-slide-to="2"></li>
		</ol>

		<!-- Wrapper for slides -->
		<div class="carousel-inner" role="listbox">
			<div class="item active">
			  <img src="img/u2.jpg" alt="...">
			  <div class="carousel-caption text-left row">
				<h2>BRINDAMOS SOLUCIONES LOGÍSTICAS Y ADUANALES PARA TU NEGOCIO</h2>
			  </div>
			</div>
			<div class="item">
			  <img src="img/u2.jpg" alt="...">
			  <div class="carousel-caption">
			    
			  </div>
			</div>
			<div class="item">
			  <img src="img/u2.jpg" alt="...">
			  <div class="carousel-caption">
			    
			  </div>
			</div>
		</div>

		<!-- Controls -->
		<a class="left carousel-control" href="#mainCarousel" role="button" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="right carousel-control" href="#mainCarousel" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>

	<div class="col-lg-6 col-lg-offset-0 col-xs-12 col-xs-offset-0 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-0 bigTop">
		<img src="img/u71.jpg" class="img-responsive">
	</div>
	
	<div class="col-lg-6 col-lg-offset-0 col-xs-12 col-xs-offset-0 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-0 bigTop">
		<h3 class="bold specialAlign">Lorem ipsum dolor sit amet, consectetur adipisicing elit</h3>

		<small class="specialAlign col-xs-12 col-sm-12 ">sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		</small>
	</div>

	<div class="page-header col-lg-12 col-xs-12 col-sm-12 col-md-12"></div>

	<div class="col-lg-6 col-lg-offset-0 col-xs-12 col-xs-offset-0 col-sm-12  col-md-12 top">
		<img src="img/u73.jpg" class="img-responsive col-lg-6 col-lg-offset-0 col-xs-12 col-xs-offset-0 col-sm-6 col-sm-offset-0 col-md-4 col-md-offset-1">
		<img src="img/u73.jpg" class="img-responsive col-lg-6 col-lg-offset-0 col-xs-12 col-xs-offset-0 col-sm-6 col-sm-offset-0 col-md-4 col-md-offset-2">
	</div>
	<div class="col-lg-6 col-lg-offset-0 col-xs-12 col-xs-offset-0 col-sm-8 col-sm-offset-2 ">
		<h3 class="bold specialAlign">Lorem ipsum dolor sit amet, consectetur adipisicing elit</h3>
		<small class="specialAlign col-xs-12">sed do eiusmod hola mundo
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		</small>
	</div>
</div>

<div class="top"></div>

<div class=" row  top blue">
	<div class="col-lg-6 col-xs-12 col-sm-12 col-md-6">
		<h2 class="textWhite specialAlign">Lorem ipsum dolor sit amet, consectetur </h2>
		<h4 class="textWhite specialAlign top"> adipisicing elit </h4>
	</div>
	<div class="col-lg-5 col-xs-12 col-sm-12 col-md-6 bot">
		<form class="textWhite ">
			<div class="row">

				<div class="col-lg-2  col-xs-2  col-sm-2 col-md-2 text-right"><label for="exampleInputEmail1">Texto</label></div>
				<div class="col-lg-10 col-xs-10"><input type="text" class="form-control" id="exampleInputEmail1" placeholder="placeHolder"></div>
			
				<div class="col-lg-2  col-xs-2  col-sm-2 col-md-2 text-right top"><label for="exampleInputEmail1">Texto</label></div>
				<div class="col-lg-10 col-xs-10 top"><input type="text" class="form-control" id="exampleInputEmail1" placeholder="placeHolder"></div>
			
				<div class="col-lg-2  col-xs-2  col-sm-2 col-md-2 text-right top"><label for="exampleInputEmail1">Texto</label></div>
				<div class="col-lg-10 col-xs-10 top"><input type="text" class="form-control" id="exampleInputEmail1" placeholder="placeHolder"></div>
			
				<div class="col-lg-12 col-xs-12 top">
					<button class="btn btn-danger col-lg-3 col-lg-offset-9 col-xs-6 col-xs-offset-3 col-md-6 col-md-offset-6">Acción</button>
				</div>
				 
			
			</div>
		  
		</form>
	</div>
		
</div>

<div class="row">
	<div class="col-lg-12 col-xs-12 col-sm-12 col-md-12 bigTop specialAlign">
		Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	</div>
	<div class="page-header col-lg-12 col-xs-12 col-sm-12 col-md-12"></div>
</div>