<script src="js/index/index.js"></script>
<?php if ($_POST): ?>
	
	<?php

	$nombre 	= $_POST['nombre'];
	$empresa 	= $_POST['empresa'];
	$email 		= $_POST['email'];
	$telefono 	= $_POST['telefono'];
	$mensaje 	= $_POST['mensaje'];
	$servicio       = $_POST['cbServicio'];

	$bodyMessage = 'Nombre: '.$nombre.'<br>Empresa: '.$empresa.'<br>Email: '.$email.'<br>Telefono: '.$telefono.'<br>Mensaje: '.$mensaje.'<br><br> Ponte en contacto con el<br>Tipo de servicio: '.$servicio;

	require 'PHPMailer/PHPMailerAutoload.php';

	$mail = new PHPMailer;

	$mail->isSMTP();                                      	// Set mailer to use SMTP
	$mail->Host = ' mail.itrademexico.mx';  		// Specify main and backup SMTP servers
	$mail->SMTPAuth = true;                               	// Enable SMTP authentication
	$mail->Password = 'ItradeMexic0';                           // SMTP password
	$mail->Username = 'website@itrademexico.mx';                 	// SMTP username
	$mail->SMTPSecure = 'ssl';                            	// Enable TLS encryption, `ssl` also accepted
	$mail->Port = 465;                                    	// TCP port to connect to

	$mail->setFrom('website@itrademexico.mx', 'CONTACTO ITRADE WEBSITE ');
	$mail->addAddress('luis.contreras@itrademexico.com.mx', $nombre);  // Add a recipient

	$mail->isHTML(true);                                  	// Set email format to HTML

	$mail->Subject = 'CONTACTO ITRADE WEBSITE';
        
        $body = file_get_contents($_SERVER['DOCUMENT_ROOT'].'/files/email/contact_email.html');
        $body = str_replace('@@nombre', $nombre, $body);
        $body = str_replace('@@empresa', $empresa, $body);
        $body = str_replace('@@email', $email, $body);
        $body = str_replace('@@telefono', $telefono, $body);
        $body = str_replace('@@servicio', $servicio, $body);
        $body = str_replace('@@mensaje', $mensaje, $body);

	$mail->Body    = $body;

	if(!$mail->send()) 
	{?>
	    <div class="alert alert-danger" role="alert">Lo siento <?php echo $nombre?> no pudimos enviar el correo </div>
    <?php 
	} else 
	{?>
		<div class="alert alert-success" role="alert">Muchas gracias <?php echo $nombre ?> por enviar tus datos, nos pondremos en contacto a la brevedad .... </div>
   	<?php 
	}

	?>

<?php endif ?>


<div class="row">
	<div id="mainCarousel" class="carousel slide col-lg-12 col-md-12 col-sm-12 col-xs-12" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators" style="top: 445px;">
		<li data-target="#mainCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#mainCarousel" data-slide-to="1"></li>
		<li data-target="#mainCarousel" data-slide-to="2"></li>
                <li data-target="#mainCarousel" data-slide-to="3"></li>
		</ol>

		<!-- Wrapper for slides -->
		<div class="carousel-inner" role="listbox">
			<div class="item active">
			  <img src="img/B1.jpg" alt="...">
			  <div class="carousel-caption text-left row hidden-xs hidden-sm">
				<h2 id="textCar1"><?php echo  $this->translate('SOLUCIONES LOGISTICAS Y ADUANALES')?></h2>
			  </div>
			</div>
			<div class="item">
			  <a href="/<?php echo lan?>/servicios"><img src="img/B2.jpg" alt="..."></a>
			  <div class="carousel-caption text-left row hidden-xs hidden-sm top"><br><br>
				<h2 id="textCar2"><?php echo  $this->translate('RAPIDEZ, EFICENCIA  Y SEGURIDAD')?></h2>
				<h4><?php echo  $this->translate('Lee mas acerca de nuestros servicios')?></h4>
			  </div>
			</div>
			<div class="item">
			  <img src="img/B3.jpg" alt="...">
			  <div class="carousel-caption text-left row hidden-xs hidden-sm">
				<h2 id="textCar3"><?php echo  $this->translate('COMIENZA A EXPORTAR HOY MISMO')?></h2>
			  </div>
			</div>
			<div class="item">
			  <img src="img/B4.jpg" alt="...">
			  <div class="carousel-caption text-left row hidden-xs hidden-sm">
				<h2 id="textCar4"><?php echo  $this->translate('ASESORIA EN LOGISTICA Y COMERCIO EXTERIOR')?></h2>
			  </div>
			</div>

		</div>

		<!-- Controls -->
		<a class="left carousel-control" href="#mainCarousel" role="button" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="right carousel-control" href="#mainCarousel" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>

	<div class="col-lg-6 col-lg-offset-0 col-xs-12 col-xs-offset-0 col-sm-12 col-md-6 col-md-offset-0 bigTop">
            <img src="img/u71.jpg" class="img-responsive">
	</div>
	
	<div class="col-lg-6 col-lg-offset-0 col-xs-12 col-xs-offset-0 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-0 top">

		<small class="specialAlign col-xs-12 col-sm-12 ">
		<h3 class="bold specialAlign"><?php echo  $this->translate('Bienvenido a ITRADE')?></h3>
                <p style="text-align: justify"><?php echo  $this->translate('ITRADE es una empresa mexicana dedicada a brindar soluciones logísticas y aduaneras,  nuestro servicio es personalizado y atendido por personas responsables, honestas y con experiencia en comercio internacional. Lo que nos distingue es la eficiencia y resultados alcanzados. Elaboramos una planeación estratégica aduanal y logística para reducir tiempos, riesgos y costos en las importaciones y exportaciones. Nuestro compromiso es con usted y su negocio.')?></p>
                <p style="text-align: justify"><?php echo  $this->translate('Nuestra Visión es convertirnos en un departamento externo de logística para las empresas, capaz de poder ofrecer un servicio de calidad y soluciones a la demanda de nuestros clientes.')?></p>
		</small>
	</div>

	<div class="page-header col-lg-12 col-xs-12 col-sm-12 col-md-12"></div>

	<div class="col-lg-6 col-lg-offset-0 col-xs-12 col-xs-offset-0 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-0 top">
		<img src="img/shipping.jpg" class="img-responsive">
	</div>

	<div class="col-lg-6 col-lg-offset-0 col-xs-12 col-xs-offset-0 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-0 ">
		<h3 class="bold specialAlign"><?php echo  $this->translate('Especialistas en el manejo de carga y transporte')?> </h3>
		<small  class="col-xs-12" style="padding-left: 0px;text-align: justify"><?php echo  $this->translate('Elaboramos la planeación estratégica aduanal y logística de tu empresa para reducir tiempos, riesgos y costos en las importaciones y exportaciones. Ofrecemos un servicio de calidad y soluciones a la demanda de nuestros clientes.')?>
		</small>
	</div>
</div>

<div class="top"></div>


<div id="contacto" class="  row top blue">
	<div class="col-lg-4 col-xs-12 col-sm-12 col-md-4">
		<h1 class="textWhite specialAlign"><?php echo  $this->translate('CONTÁCTENOS,')?></h1>
		<h3 class="textWhite specialAlign"><?php echo  $this->translate('Podemos ayudarle.')?> </h3>
	</div>
	<div class="col-lg-8 col-xs-12 col-sm-12 col-md-8 bot ">
		<form class="textWhite" action="/" method="post">

			<div class="form-group  row">
				<div class="col-lg-4 col-lg-offset-0 col-md-4 col-sm-3 col-xs-12 formAlign ">
					<label style="margin-top: 5px;" for="nombre"><?php echo  $this->translate('Nombre')?>: *</label>
				</div>
				<div class="col-lg-8 col-md-8  col-sm-8 col-xs-12">
					<input type="text" class="form-control" id="nombre" name="nombre" required>
				</div>
			</div>

			<div class="form-group row">
				<div class="col-lg-4 col-lg-offset-0 col-md-4 col-sm-3 col-xs-12 formAlign ">
					<label style="margin-top: 5px;" for="empresa"><?php echo  $this->translate('Empresa')?>:</label>
				</div>
				<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
					<input type="text" class="form-control" id="empresa" name="empresa" >
				</div>
			</div>
			
			<div class="form-group row ">
				<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12 formAlign ">
					<label style="margin-top: 5px;" for="email"><?php echo  $this->translate('E-mail')?>: *</label>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-8 col-xs-12">
					<input type="text" class="form-control" id="email" name="email" required>
				</div>
				<div class="col-lg-2 col-md-2 col-sm-3 col-xs-12 formAlign top-sm ">
					<label style="margin-top: 5px;" for="telefono"><?php echo  $this->translate('Teléfono')?>: *</label>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-8 col-xs-12 top-sm">
					<input type="text" class="form-control" id="telefono" name="telefono" required>
				</div>
			</div>


			<div class="form-group row">
				<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12 formAlign ">
					<label style="margin-top: 5px;" for="mensaje"><?php echo  $this->translate('Mensaje')?>: *</label>
				</div>
				<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
					<textarea name="mensaje" id="mensaje" class="form-control" rows="3" required></textarea>
				</div>
			</div>

			<div class="form-group row">
				<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12 formAlign ">
					<label style="margin-top: 5px;" for="mensaje"><?php echo  $this->translate('Servicio')?>: *</label>
				</div>
				<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
					
					<select name="cbServicio" id="cbServicio" class="form-control">
						<option value="maritimo"><?php echo  $this->translate('Marítimo')?></option>
						<option value="aereo"><?php echo  $this->translate('Aéreo')?></option>
						<option value="terrestre"><?php echo  $this->translate('Terrestre')?></option>
						<option value="aduana"><?php echo  $this->translate('Aduana')?></option>
						<option value="seguro"><?php echo  $this->translate('Seguro')?></option>
					</select>
				</div>
			</div>


			<div class="form-group row">
				<div class="col-lg-3 col-lg-offset-9 col-md-3 col-md-offset-9 col-sm-4 col-sm-offset-5 col-xs-6 col-xs-offset-3 top">
					<button class="btn btn-danger  col-lg-12 col-md-10 col-sm-12 col-xs-12 "><?php echo  $this->translate('Enviar')?></button>
				</div>
			</div>
			<div class="row"></div> 

		</form>
	</div>
		
</div>