<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ITRADE ADMINISTATOR')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->appendStylesheet($this->basePath('plugins/admin/boostrapv3/css/bootstrap.min.css'))
            ->appendStylesheet($this->basePath('plugins/admin/boostrapv3/css/bootstrap-theme.min.css'))
            ->appendStylesheet($this->basePath('plugins/admin/font-awesome/css/font-awesome.css'))
            ->appendStylesheet($this->basePath('css/admin/style_itrade.css'))
        ?>
        
        <!-- BEGIN CORE JS FRAMEWORK--> 
        <script src="/plugins/admin/jquery-1.8.3.min.js" type="text/javascript"></script> 
        <script src="/plugins/admin/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script> 
        <script src="/plugins/admin/boostrapv3/js/bootstrap.min.js" type="text/javascript"></script> 
    </head>
    <body id="admin_login">
        <div class="page-content"> 
            <div class="content">  
                <?php echo $this->content?>
            </div>
        </div>
    </body>
</html>
