<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ITRADE ')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            
            ->appendStylesheet($this->basePath('plugins/admin/jquery-datatable/css/jquery.dataTables.min.css'))
            ->appendStylesheet($this->basePath('plugins/admin/datatables-responsive/css/datatables.responsive.min.css'))
            ->appendStylesheet($this->basePath('plugins/admin/bootstrap-datepicker/css/datepicker.css'))
            ->appendStylesheet($this->basePath('plugins/admin/bootstrap-timepicker/css/bootstrap-timepicker.css'))
            ->appendStylesheet($this->basePath('plugins/admin/bootstrap-select2/select2.css'))
            ->appendStylesheet($this->basePath('plugins/admin/pace/pace-theme-flash.css'))
            ->appendStylesheet($this->basePath('plugins/admin/jquery-scrollbar/jquery.scrollbar.css'))
            ->appendStylesheet($this->basePath('plugins/admin/boostrapv3/css/bootstrap.min.css'))
            ->appendStylesheet($this->basePath('plugins/admin/boostrapv3/css/bootstrap-theme.min.css'))
            ->appendStylesheet($this->basePath('plugins/admin/font-awesome/css/font-awesome.css'))
            ->appendStylesheet($this->basePath('css/admin/animate.min.css'))
            ->appendStylesheet($this->basePath('css/admin/style.css'))
            ->appendStylesheet($this->basePath('css/admin/style_itrade.css'))
            ->appendStylesheet($this->basePath('css/admin/responsive.css'))
            ->appendStylesheet($this->basePath('css/admin/custom-icon-set.css')) 
            ->appendStylesheet($this->basePath('css/admin/custom-icon-set.css'))  
            ->appendStylesheet($this->basePath('plugins/admin/jquery-notifications/css/messenger.min.css')) 
            ->appendStylesheet($this->basePath('plugins/admin/jquery-notifications/css/messenger-theme-future.min.css'))
//            ->appendStylesheet($this->basePath('plugins/admin/data-tables/DT_bootstrap.min.css'))
        ?>
        
        <!-- BEGIN CORE JS FRAMEWORK--> 
        <script src="/plugins/admin/jquery-1.8.3.min.js" type="text/javascript"></script> 
        <script src="/plugins/admin/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script> 
        <script src="/plugins/admin/boostrapv3/js/bootstrap.min.js" type="text/javascript"></script> 
        <script src="/plugins/admin/breakpoints.js" type="text/javascript"></script> 
        <script src="/plugins/admin/jquery-unveil/jquery.unveil.min.js" type="text/javascript"></script> 
        <script src="/plugins/admin/jquery-block-ui/jqueryblockui.js" type="text/javascript"></script> 
        <script src="/plugins/admin/bootstrap-select2/select2.min.js" type="text/javascript"></script>
        <script src="/plugins/admin/bootstrap-select2/select2_locale_es.min.js" type="text/javascript"></script>
        <script src="/plugins/admin/bootstrap-datepicker/js/bootstrap-datepicker.js" type="text/javascript"></script>
	<script src="/plugins/admin/bootstrap-timepicker/js/bootstrap-timepicker.min.js" type="text/javascript"></script>
        <script src="/plugins/admin/moment.js" type="text/javascript"></script>
        <script src="/plugins/admin/jquery-notifications/js/messenger.min.js" type="text/javascript"></script>
         <script src="/plugins/admin/jquery-url-object/jquery_url_object.js" type="text/javascript"></script>
        
        
      
        <!-- END CORE JS FRAMEWORK --> 
        <!-- BEGIN PAGE LEVEL JS --> 	
        <script src="/plugins/admin/jquery-scrollbar/jquery.scrollbar.min.js" type="text/javascript"></script>
        <script src="/plugins/admin/pace/pace.min.js" type="text/javascript"></script>  
        <script src="/plugins/admin/jquery-numberAnimate/jquery.animateNumbers.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS --> 	
        <!-- BEGIN CORE TEMPLATE JS --> 
        <script src="/js/admin/core.js" type="text/javascript"></script> 
        <script src="/js/admin/chat.js" type="text/javascript"></script> 
        <script src="/js/admin/demo.js" type="text/javascript"></script> 
        <!-- END CORE TEMPLATE JS --> 
        <!-- BEGIN DATATABLE JS --> 
        <script src="/plugins/admin/jquery-datatable/js/jquery.dataTables.js" type="text/javascript"></script>
	<script src="/plugins/admin/jquery-datatable/extra/js/dataTables.tableTools.min.js" type="text/javascript"></script>
	<script type="text/javascript" src="/plugins/admin/datatables-responsive/js/datatables.responsive.js"></script>
	<script type="text/javascript" src="/plugins/admin/datatables-responsive/js/lodash.min.js"></script>
        <script type="text/javascript" src="/plugins/admin/jquery-datatable/extra/js/dataTablesInitilization.js"></script>

        <!-- END DATATABLE JS --> 
        <script src="/js/admin/form/form.js" type="text/javascript"></script>
        <script src="/plugins/admin/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
        

	
        
    

        
    </head>
    <body class="">
        <?php $session = new \Shared\Session\AouthSession()?>;
        <?php $session = $session->getData();?>
        <!-- BEGIN HEADER -->
        <div class="header navbar navbar-inverse" style="top: 0px;">
            <!-- BEGIN TOP NAVIGATION BAR -->
            <div class="navbar-inner">
                <!-- BEGIN NAVIGATION HEADER -->
                <div class="header-seperation"> 
                    <!-- BEGIN MOBILE HEADER -->
                    <ul class="nav pull-left notifcation-center" id="main-menu-toggle-wrapper" style="display:none">	
                        <li class="dropdown">
                            <a id="main-menu-toggle" href="#main-menu" class="">
                                <div class="iconset top-menu-toggle-white"></div>
                            </a>
                        </li>		 
                    </ul>
                    <!-- END MOBILE HEADER -->
                    <!-- BEGIN LOGO -->	
                    <a href="#">
                        <!-- <img src="logo_itrade_transparent.png" class="logo" alt="" data-src="logo_itrade_transparent.png" data-src-retina="logo_itrade_transparent.png" width="106" height="21"/>-->
                    </a>
                    <!-- END LOGO --> 
                    <!-- BEGIN LOGO NAV BUTTONS -->
                    <ul class="nav pull-right notifcation-center">	
                        <li class="dropdown" id="header_task_bar">
                            <a href="#" class="dropdown-toggle active" data-toggle="">
                                <div class="iconset top-home"></div>
                            </a>
                        </li>
                        <li class="dropdown" id="header_inbox_bar">
                            <a href="#" class="dropdown-toggle">
                                <div class="iconset top-messages"></div>
                                <span class="badge" id="msgs-badge">2</span>
                            </a>
                        </li>
                        <!-- BEGIN MOBILE CHAT TOGGLER -->
                        <li class="dropdown" id="portrait-chat-toggler" style="display:none">
                            <a href="#sidr" class="chat-menu-toggle">
                                <div class="iconset top-chat-white"></div>
                            </a>
                        </li>
                        <!-- END MOBILE CHAT TOGGLER -->				        
                    </ul>
                    <!-- END LOGO NAV BUTTONS -->
                </div>
                <!-- END NAVIGATION HEADER -->
                <!-- BEGIN CONTENT HEADER -->
                <div class="header-quick-nav"> 
                    <!-- BEGIN HEADER LEFT SIDE SECTION -->
                    <div class="pull-left"> 
                        <!-- BEGIN SLIM NAVIGATION TOGGLE -->
                        <ul class="nav quick-section">
                            <li class="quicklinks">
                                <a href="#" class="" id="layout-condensed-toggle">
                                    <div class="iconset top-menu-toggle-dark"></div>
                                </a>
                            </li>
                        </ul>
                        <!-- END SLIM NAVIGATION TOGGLE -->				
                        <!-- BEGIN HEADER QUICK LINKS -->
                        <ul class="nav quick-section">
                            <li class="quicklinks"><a href="#" class=""><div class="iconset top-reload"></div></a></li>
                            <li class="quicklinks"><span class="h-seperate"></span></li>
                            <li class="quicklinks"><a href="#" class=""><div class="iconset top-tiles"></div></a></li>
                            <!-- BEGIN SEARCH BOX -->
                            <li class="m-r-10 input-prepend inside search-form no-boarder">
                                <span class="add-on"><span class="iconset top-search"></span></span>
                                <input name="" type="text" class="no-boarder" placeholder="Busqueda rapida" style="width:250px;">
                            </li>
                            <!-- END SEARCH BOX -->
                        </ul>
                        <!-- BEGIN HEADER QUICK LINKS -->				
                    </div>
                    <!-- END HEADER LEFT SIDE SECTION -->
                    <!-- BEGIN HEADER RIGHT SIDE SECTION -->
                    <div class="pull-right"> 
                        <div class="chat-toggler">	
                            <!-- BEGIN NOTIFICATION CENTER -->
                            <a href="#" class="dropdown-toggle" id="my-task-list" data-placement="bottom" data-content="" data-toggle="dropdown" data-original-title="Notifications">
                                <div class="user-details"> 
                                    <div class="username">
                                        <span class="badge badge-important">3</span>&nbsp;<?php echo $session['empleado_nombre']?><span class="bold">&nbsp;<?php echo $session['empleado_apellidopaterno']?></span>									
                                    </div>						
                                </div> 
                                <div class="iconset top-down-arrow"></div>
                            </a>	
                            <div id="notification-list" style="display:none">
                                <div style="width:300px">
                                    <!-- BEGIN NOTIFICATION MESSAGE -->
                                    <div class="notification-messages info">
                                        <div class="user-profile">
                                            <img src="/img/admin/profiles/d.jpg" alt="" data-src="/img/admin/profiles/d.jpg" data-src-retina="/img/admin/profiles/d2x.jpg" width="35" height="35">
                                        </div>
                                        <div class="message-wrapper">
                                            <div class="heading">Title of Notification</div>
                                            <div class="description">Description...</div>
                                            <div class="date pull-left">A min ago</div>										
                                        </div>
                                        <div class="clearfix"></div>									
                                    </div>
                                    <!-- END NOTIFICATION MESSAGE -->	
                                </div>				
                            </div>
                            <!-- END NOTIFICATION CENTER -->
                            <!-- BEGIN PROFILE PICTURE -->
                            <div class="profile-pic"> 
                                <img src="<?php echo $session['empleado_foto']?>" alt="" data-src="<?php echo $session['empleado_foto']?>" data-src-retina="<?php echo $session['empleado_foto']?>" width="35" height="35" /> 
                            </div>  
                            <!-- END PROFILE PICTURE -->     			
                        </div>
                        <!-- BEGIN HEADER NAV BUTTONS -->
                        <ul class="nav quick-section">
                            <!-- BEGIN SETTINGS -->
                            <li class="quicklinks"> 
                                <a data-toggle="dropdown" class="dropdown-toggle pull-right" href="#" id="user-options">						
                                    <div class="iconset top-settings-dark"></div> 	
                                </a>
                                <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="user-options">
                                    <li><a href="#">Link 1</a></li>
                                    <li><a href="#">Link 2&nbsp;&nbsp;<span class="badge badge-important animated bounceIn">2</span></a></li>
                                    <li class="divider"></li>                
                                    <li><a href="/login/out"><i class="fa fa-power-off"></i>&nbsp;&nbsp;Cerrar sesión</a></li>
                                </ul>
                            </li>
                            <!-- END SETTINGS -->

                            <!-- BEGIN CHAT SIDEBAR TOGGLE -->

                            <!-- END CHAT SIDEBAR TOGGLE --> 
                        </ul>
                        <!-- END HEADER NAV BUTTONS -->
                    </div>
                    <!-- END HEADER RIGHT SIDE SECTION -->
                </div> 
                <!-- END CONTENT HEADER --> 
            </div>
            <!-- END TOP NAVIGATION BAR --> 
        </div>
        <!-- END HEADER -->

        <!-- BEGIN CONTENT -->
        <div class="page-container row-fluid">
            <!-- BEGIN SIDEBAR -->
            <!-- BEGIN MENU -->
            <div class="page-sidebar" id="main-menu"> 
                <div class="page-sidebar-wrapper scrollbar-dynamic" id="main-menu-wrapper">
                    <!-- BEGIN MINI-PROFILE -->
                    <div class="user-info-wrapper">	
                        <div class="profile-wrapper">
                            <img src="<?php echo $session['empleado_foto']?>" alt="" data-src="<?php echo $session['empleado_foto']?>" data-src-retina="<?php echo $session['empleado_foto']?>" width="69" height="69" />
                        </div>
                        <div class="user-info">
                            <div class="greeting">Bienvenido</div>
                            <div class="username"><?php echo $session['empleado_nombre']?> <span class="semi-bold"><?php echo $session['empleado_apellidopaterno']?></span></div>
                            <div class="status">Estatus<a href="#"><div class="status-icon green"></div>Disponible</a></div>
                        </div>
                    </div>
                    <!-- END MINI-PROFILE -->
                    <!-- BEGIN SIDEBAR MENU -->	
                    
                    <ul>	
                        <!-- BEGIN SELECTED LINK -->
                        <li navbar="dashboard" class="start active">
                            <a href="#">
                                <i class="icon-custom-home"></i>
                                <span class="title">Escritorio</span>
                                <span class="selected"></span>
                                <!--<span class="badge badge-important pull-right">5</span>-->
                            </a>
                        </li>
                        <!-- END SELECTED LINK -->
                        <!-- BEGIN TWO LEVEL MENU -->
                        <li class="">
                            <a href="javascript:;">
                                <i class="fa fa-folder-open"></i>
                                <span class="title">Catálogo</span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">
                                <li><a href="javascript:;">Clientes</a></li>
                                <li><a href="/catalogo/empleados">Empleados</a></li>
                                <li>
                                    <a href="javascript:;">
                                        <span class="title">Gastos facturación</span>
                                        <span class="arrow"></span>
                                    </a>
                                    <ul class="sub-menu">
                                        <li><a href="/catalogo/gastos/categorias">Categorias</a></li>
                                        <li><a href="/catalogo/gastos">Conceptos</a></li>
                                    </ul>
                                </li>
                                <li><a href="/catalogo/proveedores">Proveedores</a></li>
                                <li><a href="javascript:;">Servicios</a></li>
                            </ul>
                        </li>
                        <!-- END TWO LEVEL MENU -->
                        <!-- BEGIN BADGE LINK -->
                        <li class="">
                            <a href="#">
                                <i class="fa fa-envelope"></i>
                                <span class="title">Link 2</span>
                                <span class="badge badge-disable pull-right">203</span>
                            </a>
                        </li>
                        <!-- END BADGE LINK -->     
                        <!-- BEGIN SINGLE LINK -->
                        <li class="">
                            <a href="#">
                                <i class="fa fa-flag"></i>
                                <span class="title">Link 3</span>
                            </a>
                        </li>
                        <!-- END SINGLE LINK -->    
                        <!-- BEGIN ONE LEVEL MENU -->
                        <li class="">
                            <a href="javascript:;">
                                <i class="icon-custom-ui"></i>
                                <span class="title">Link 4</span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">
                                <li><a href="#">Sub Link 1</a></li>
                            </ul>
                        </li>
                        <!-- END ONE LEVEL MENU -->
                        			
                    </ul>
                    <!-- END SIDEBAR MENU -->
                    <!-- BEGIN SIDEBAR WIDGETS -->

                    <div class="clearfix"></div>
                    <!-- END SIDEBAR WIDGETS --> 
                </div>
            </div>
            <!-- BEGIN SCROLL UP HOVER -->
            <a href="#" class="scrollup">Scroll</a>
            <!-- END SCROLL UP HOVER -->
            <!-- END MENU -->
            <!-- BEGIN SIDEBAR FOOTER WIDGET -->
            <!-- END SIDEBAR FOOTER WIDGET -->
            <!-- END SIDEBAR --> 
            <!-- BEGIN PAGE CONTAINER-->
            <div class="page-content"> 
                <div class="content">  
                    <!-- BEGIN PAGE TITLE -->
                    <?php echo $this->content?>
                    <!-- END PAGE TITLE -->
                    <!-- BEGIN PlACE PAGE CONTENT HERE -->

                    <!-- END PLACE PAGE CONTENT HERE -->
                </div>
            </div>
            <!-- END PAGE CONTAINER -->
            <!-- BEGIN CHAT --> 
            <div class="chat-window-wrapper">
                <div id="main-chat-wrapper" class="inner-content">
                    <div class="chat-window-wrapper scroller scrollbar-dynamic" id="chat-users">
                        <!-- BEGIN CHAT HEADER -->
                        <div class="chat-header">	
                            <!-- BEGIN CHAT SEARCH BAR -->
                            <div class="pull-left">
                                <input type="text" placeholder="search">
                            </div>
                            <!-- END CHAT SEARCH BAR -->
                            <!-- BEGIN CHAT QUICKLINKS -->		
                            <div class="pull-right">
                                <a href="#" class=""><div class="iconset top-settings-dark"></div></a>
                            </div>
                            <!-- END CHAT QUICKLINKS -->			
                        </div>
                        <!-- END CHAT HEADER -->	
                        <!-- BEGIN GROUP WIDGET -->
                        <div class="side-widget">
                            <div class="side-widget-title">group chats</div>
                            <div class="side-widget-content">
                                <div id="groups-list">
                                    <ul class="groups">
                                        <li><a href="#"><div class="status-icon green"></div>Group Chat 1</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- END GROUP WIDGET -->
                        <!-- BEGIN FAVORITES WIDGET -->
                        <div class="side-widget">
                            <div class="side-widget-title">favorites</div>
                            <div class="side-widget-content">
                                <!-- BEGIN SAMPLE CHAT -->
                                <div class="user-details-wrapper active" data-chat-status="online" data-chat-user-pic="/img/admin/profiles/d.jpg" data-chat-user-pic-retina="/img/admin/profiles/d2x.jpg" data-user-name="Jane Smith">
                                    <!-- BEGIN PROFILE PIC -->
                                    <div class="user-profile">
                                        <img src="/img/admin/profiles/d.jpg" alt="" data-src="/img/admin/profiles/d.jpg" data-src-retina="/img/admin/profiles/d2x.jpg" width="35" height="35">
                                    </div>
                                    <!-- END PROFILE PIC -->
                                    <!-- BEGIN MESSAGE -->
                                    <div class="user-details">
                                        <div class="user-name">Jane Smith</div>
                                        <div class="user-more">Message...</div>
                                    </div>
                                    <!-- END MESSAGE -->
                                    <!-- BEGIN MESSAGES BADGE -->
                                    <div class="user-details-status-wrapper">
                                        <span class="badge badge-important">3</span>
                                    </div>
                                    <!-- END MESSAGES BADGE -->
                                    <!-- BEGIN STATUS -->
                                    <div class="user-details-count-wrapper">
                                        <div class="status-icon green"></div>
                                    </div>
                                    <!-- END STATUS -->
                                    <div class="clearfix"></div>
                                </div>
                                <!-- END SAMPLE CHAT -->	
                            </div>
                        </div>
                        <!-- END FAVORITES WIDGET -->
                        <!-- BEGIN MORE FRIENDS WIDGET -->
                        <div class="side-widget">
                            <div class="side-widget-title">more friends</div>
                            <div class="side-widget-content" id="friends-list">
                                <!-- BEGIN SAMPLE CHAT -->
                                <div class="user-details-wrapper" data-chat-status="online" data-chat-user-pic="/img/admin/profiles/d.jpg" data-chat-user-pic-retina="/img/admin/profiles/d2x.jpg" data-user-name="Jane Smith">
                                    <!-- BEGIN PROFILE PIC -->
                                    <div class="user-profile">
                                        <img src="/img/admin/profiles/d.jpg" alt="" data-src="/img/admin/profiles/d.jpg" data-src-retina="/img/admin/profiles/d2x.jpg" width="35" height="35">
                                    </div>
                                    <!-- END PROFILE PIC -->
                                    <!-- BEGIN MESSAGE -->
                                    <div class="user-details">
                                        <div class="user-name">Jane Smith</div>
                                        <div class="user-more">Message...</div>
                                    </div>
                                    <!-- END MESSAGE -->
                                    <!-- BEGIN MESSAGES BADGE -->
                                    <div class="user-details-status-wrapper">
                                        <span class="badge badge-important">3</span>
                                    </div>
                                    <!-- END MESSAGES BADGE -->
                                    <!-- BEGIN STATUS -->
                                    <div class="user-details-count-wrapper">
                                        <div class="status-icon green"></div>
                                    </div>
                                    <!-- END STATUS -->
                                    <div class="clearfix"></div>
                                </div>
                                <!-- END SAMPLE CHAT -->
                            </div>		
                        </div>
                        <!-- END MORE FRIENDS WIDGET -->
                    </div>		
                    <!-- BEGIN DUMMY CHAT CONVERSATION -->
                    <div class="chat-window-wrapper" id="messages-wrapper" style="display:none">
                        <!-- BEGIN CHAT HEADER BAR -->
                        <div class="chat-header">	
                            <!-- BEGIN SEARCH BAR -->
                            <div class="pull-left">
                                <input type="text" placeholder="search">
                            </div>		
                            <!-- END SEARCH BAR -->
                            <!-- BEGIN CLOSE TOGGLE -->
                            <div class="pull-right">
                                <a href="#" class=""><div class="iconset top-settings-dark"></div></a>
                            </div>	
                            <!-- END CLOSE TOGGLE -->				
                        </div>
                        <div class="clearfix"></div>
                        <!-- END CHAT HEADER BAR -->
                        <!-- BEGIN CHAT BODY -->
                        <div class="chat-messages-header">
                            <div class="status online"></div>
                            <span class="semi-bold">Jane Smith(Typing..)</span>
                            <a href="#" class="chat-back"><i class="icon-custom-cross"></i></a>
                        </div>
                        <!-- BEGIN CHAT MESSAGES CONTAINER -->
                        <div class="chat-messages scrollbar-dynamic clearfix">
                            <!-- BEGIN TIME STAMP EXAMPLE -->
                            <div class="sent_time">Yesterday 11:25pm</div>
                            <!-- END TIME STAMP EXAMPLE -->
                            <!-- BEGIN EXAMPLE CHAT MESSAGE -->
                            <div class="user-details-wrapper">
                                <!-- BEGIN MESSENGER PROFILE -->
                                <div class="user-profile">
                                    <img src="/img/admin/profiles/d.jpg" alt="" data-src="/img/admin/profiles/d.jpg" data-src-retina="/img/admin/profiles/d2x.jpg" width="35" height="35">
                                </div>
                                <!-- END MESSENGER PROFILE -->
                                <!-- BEGIN MESSENGER MESSAGE -->
                                <div class="user-details">
                                    <div class="bubble">Hello, You there?</div>
                                </div>
                                <!-- END MESSENGER MESSAGE -->					
                                <div class="clearfix"></div>
                                <!-- BEGIN TIMESTAMP ON CLICK TOGGLE -->
                                <div class="sent_time off">Yesterday 11:25pm</div>
                                <!-- END TIMESTAMP ON CLICK TOGGLE -->
                            </div>
                            <!-- END EXAMPLE CHAT MESSAGE -->
                            <!-- BEGIN TIME STAMP EXAMPLE -->
                            <div class="sent_time">Today 11:25pm</div>
                            <!-- BEGIN TIME STAMP EXAMPLE -->				
                            <!-- BEGIN EXAMPLE CHAT MESSAGE (FROM SELF) -->
                            <div class="user-details-wrapper pull-right">
                                <!-- BEGIN MESSENGER MESSAGE -->
                                <div class="user-details">
                                    <div class="bubble sender">Let me know when you free</div>
                                </div>					
                                <!-- END MESSENGER MESSAGE -->
                                <div class="clearfix"></div>
                                <!-- BEGIN TIMESTAMP ON CLICK TOGGLE -->
                                <div class="sent_time off">Sent On Tue, 2:45pm</div>
                                <!-- END TIMESTAMP ON CLICK TOGGLE -->
                            </div>	
                            <!-- END EXAMPLE CHAT MESSAGE (FROM SELF) -->	
                        </div>
                        <!-- END CHAT MESSAGES CONTAINER -->
                    </div>
                    <div class="chat-input-wrapper" style="display:none">
                        <textarea id="chat-message-input" rows="1" placeholder="Type your message"></textarea>
                    </div>
                    <div class="clearfix"></div>
                    <!-- END DUMMY CHAT CONVERSATION -->
                </div>
            </div>
            <!-- END CHAT --> 
        </div>
    </body>
</html>
