<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('ITRADE'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/.ico'))
                        ->prependStylesheet($this->basePath('fonts/icons.css')) 
                        ->prependStylesheet($this->basePath('css/style.css')) 
                        ->prependStylesheet($this->basePath('css/bootstrap.css'))
                        ->prependStylesheet($this->basePath('css/jasny-bootstrap.css')) 
                        ?>


        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/login.js'))
            ->prependFile($this->basePath('js/comun.js'))
            ->prependFile($this->basePath('js/bootstrap.js'))
            ->prependFile($this->basePath('js/jasny-bootstrap.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body class="login">
       
        <div class="container-fluid">
            <?php echo $this->content; ?>
            
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
