<img class="img-Back"src="img/back.png" alt="">

<div class="row top ">
	
	<div class="col-lg-7 col-lg-offset-5 text-center panel-login">
		<div class="row">
			<div class="col-lg-4">
				<h1>Iniciar Sesión</h1>
				<input type="text" class="form-control username" placeholder="Nombre de usuario">
				
				<div class="input-group">
					<input type="text" class="form-control password" placeholder="Contraseña">
		        	<span class="input-group-addon "><span class="glyphicon glyphicon-menu-right"></span></span>
		        </div>
	        </div>

		</div>
		
		
		<div class="row">
			<div class="page-header col-lg-2 col-lg-offset-1 ">
				<div class="checkbox top ">
					<label class="white">
						<input type="checkbox"> No cerrar seción
					</label>
				</div>
				
			</div>
		</div>

		<div class="row">
			
			<a class="col-lg-4 col-lg-offset- "href="">
				<div class="white">Olvidaste tu nombre de usuario o contraseña?
				</div>
			</a>
			
		</div>

	</div>

</div>