<script src="js/login/login.js"></script>

<a href="<?php echo $_SERVER['HTTP_REFERER']; ?>">
	<img class="img-Back"src="img/back.png" alt="">
</a>

<div class="row top ">
	


	<div class="col-lg-7 col-lg-offset-5 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 text-center panel-login">
		<div class="row">
			<div class="col-lg-4">
				<h1>Iniciar Sesión</h1>
				<input id="txtUser" type="text" class="form-control username" placeholder="Nombre de usuario">
				
				<div class="form-group has-feedback ">
					<input name="txtPass" id="txtPass"type="text" class="form-control password" placeholder="Contraseña" /> 	 	
					<!--<span  id="plhPass"class="icon-right-arrow form-control-feedback"></span>-->
					<img  id="plhPass" class="form-control-feedback" src="/img/pass.png" alt="">
				</div>
	        </div>

		</div>
		
		
		<div class="row">
			<div class="page-header col-lg-4  ">
				<div class="checkbox top ">
					<label class="white">
						<input type="checkbox"> No cerrar sesión
					</label>
				</div>
				
			</div>
		</div>

		<div class="row">
			
			<a class="col-lg-4 col-lg-offset- "href="">
				<div class="white">Olvidaste tu nombre de usuario o contraseña?
				</div>
			</a>
			
		</div>

	</div>

</div>

