<div class="form_container">
    <ul class="breadcrumb">
        <li>
            <a href="/clientes">Clientes</a>
        </li>
        <li>
            <a href="/clientes/ver/<?php echo $cliente->getIdcliente()?>"><?php echo $cliente->getClienteRazonsocial()?></a>
        </li>
        <li>
            <a href="/clientes/ver/<?php echo $cliente->getIdcliente()?>?active=expedientes">Expedientes</a>
        </li>
        <li>
            <a class="active" href="/clientes/ver/<?php echo $cliente->getIdcliente()?>/expedientes/ver/<?php echo $entity->getIdexpediente()?>"><?php echo $entity->getExpedienteFolio()?></a>
        </li>
    </ul>
    <div class="page-title">
        <h3><span class="semi-bold"><?php echo $entity->getExpedienteFolio()?></span></h3>
    </div>
    <?php 
        //$form->setAttribute('action', '/clientes/ver/'.$cliente->getIdcliente().'/expedientes/nuevo');
        //$form->setAttribute('novalidate', true);
        //$form->setAttribute('enctype', 'multipart/form-data');

        //echo $this->form()->openTag($form); 
    ?>
    <div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4><span class="semi-bold">Información general</span></h4>
                    <div class="tools">
                        <a class="collapse" href="javascript:;"></a>
                    </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formHidden($form->get('idexpediente')) ?> 
                                    <?php echo $this->formLabel($form->get('expediente_estatus')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formSelect($form->get('expediente_estatus')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('expediente_fechainicio')) ?> 
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('expediente_fechainicio')) ?> 
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('expediente_fechafin')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                         <?php echo $this->formText($form->get('expediente_fechafin')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="grid simple">
                <div class="grid-title no-border">
                    <div class="grid-title no-border">
                        <h4><span class="semi-bold">Facturación</span></h4>
                        <div class="tools">
                            <a id="user-options" class="dropdown-toggle config" href="javascript:;" data-toggle="dropdown"></a>
                            <a class="collapse" href="javascript:;"></a>

                            <ul class="dropdown-menu pull-right" aria-labelledby="user-options" role="menu">
                                <li>
                                    <a id="nuevo_cargo" style="background: none"href="javascript:void(0)"><i class="fa fa-plus"></i> Nuevo cargo</a>
                                    <a id="ver_cargos" style="background: none"href="javascript:void(0)"><i class="fa fa-eye"></i>Ver cargos</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="grid-body no-border">
                        <table id="table_facturacion" class="table">
                            <thead>
                                <tr>
                                    <th>Cargos a recibir</th>
                                    <th>Cargos conocidos</th>
                                    <th>Conceptos de facturación</th>
                                    <th>Sujetos a IVA</th>
                                    <th>No sujetos a IVA</th>
                                    <th>Opciones</th>
                                </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="grid simple">
                <div class="grid-title no-border">
                    <div class="grid-title no-border">
                        <h4><span class="semi-bold">Servicios</span></h4>
                        <div class="tools">
                            <a class="collapse" href="javascript:;"></a>
                        </div>
                    </div>
                    <div class="grid-body no-border">
                        <table id="table_facturacion" class="table">
                            <thead>
                                <tr>
                                    <th>Creación</th>
                                    <th>Servicio</th>
                                    <th>Estatus (Actual)</th>
                                    <th>Fecha final</th>
                                    <th>Opciones</th>
                                </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="grid simple ">
                    <div class="grid-title no-border">
                        <h4><span class="semi-bold">Archivos</span></h4>
                        <div class="tools">
                            <a class="collapse" href="javascript:;"></a>
                        </div>
                    </div>
                    <div class="grid-body no-border">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="row-fluid" style="margin-top: 20px;">
                                    <div class="dropzone" id="mydropzone"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <div class="form-actions">
                <div class="row">
                    <div class="pull-right">
                        <button btn_action="submit" class="btn btn-primary btn-cons" type="button">Guardar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php 
        //echo $this->form()->closeTag(); 
    ?>
</div>
<!--CUSTOM SCRIPT-->
<script src="/js/admin/expedientes/expediente.js"></script>
<!--DROPZONE-->
<script src="/plugins/admin/dropzone/dropzone.js"></script>
<script src="/plugins/admin/download/download.js"></script>
<link rel="stylesheet" type="text/css" href="/plugins/admin/dropzone/css/dropzone.css">
<script type="text/javascript">
    $(document).ready(function() {
        //FORM BIND
        var $form = $('.form_container').expediente({successMessages:<?php echo $successMessages?>});
        $form.formBind();

    });
</script>



