<div class="form_container">
    <ul class="breadcrumb">
        <li>
            <a href="/clientes">Clientes</a>
        </li>
        <li>
            <a href="/clientes/ver/<?php echo $cliente->getIdcliente()?>"><?php echo $cliente->getClienteRazonsocial()?></a>
        </li>
        <li>
            <a href="/clientes/ver/<?php echo $cliente->getIdcliente()?>?active=expedientes">Expedientes</a>
        </li>
        <li>
            <a class="active" href="/clientes/ver/<?php echo $cliente->getIdcliente()?>/expedientes/ver/<?php echo $entity->getIdexpediente()?>"><?php echo $entity->getExpedienteFolio()?></a>
        </li>
    </ul>
    <div class="page-title">
        <h3><span class="semi-bold"><?php echo $entity->getExpedienteFolio()?></span></h3>
    </div>
    <?php 
        //$form->setAttribute('action', '/clientes/ver/'.$cliente->getIdcliente().'/expedientes/nuevo');
        //$form->setAttribute('novalidate', true);
        //$form->setAttribute('enctype', 'multipart/form-data');

        //echo $this->form()->openTag($form); 
    ?>
    <div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4><span class="semi-bold">Información general</span></h4>
                    <div class="tools">
                        <a class="collapse" href="javascript:;"></a>
                    </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formHidden($form->get('idcliente')) ?> 
                                    <?php echo $this->formHidden($form->get('idexpediente')) ?> 
                                    <?php echo $this->formHidden($form->get('expediente_tipo')) ?> 
                                    <?php echo $this->formLabel($form->get('expediente_estatus')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formSelect($form->get('expediente_estatus')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('expediente_fechainicio')) ?> 
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('expediente_fechainicio')) ?> 
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('expediente_fechafin')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                         <?php echo $this->formText($form->get('expediente_fechafin')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <b>CONSIGNATARIO</b>
                            <p><?php echo $consignatario?></p>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <b>EMBARCADOR</b>
                            <p><?php echo $embarcador?></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="grid simple">
                <div class="grid-title no-border">
                    <div class="grid-title no-border">
                        <h4><span class="semi-bold">Facturación MXN</span></h4>
                        <div class="tools">
                            <a id="user-options" class="dropdown-toggle config" href="javascript:;" data-toggle="dropdown"></a>
                            <a class="collapse" href="javascript:;"></a>

                            <ul class="dropdown-menu pull-right" aria-labelledby="user-options" role="menu">
                                <li>
                                    <a id="nuevo_cargo_mxn" style="background: none"href="javascript:void(0)"><i class="fa fa-plus"></i> Nuevo cargo</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="grid-body no-border">
                        <?php setlocale(LC_MONETARY, 'en_US'); ?>
                        <table id="table_facturacion" class="table table-striped">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Cargos estimados</th>
                                    <th>Cargos realizados</th>
                                    <th>Conceptos de facturación</th>
                                    <th>Venta sujeta a IVA</th>
                                    <th>Venta no sujeta a IVA</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($facturacion as $key => $value) :?>
                                    <tr class="main"id="<?php echo $value['id']?>">
                                        <td class="center"><i class="fa fa-plus-circle collapse"></i></td>
                                        <td><?php echo money_format('%(#10n', (float)$value['cargos_recibir'])?></td>
                                        <td><?php echo money_format('%(#10n', (float)$value['cargos_conocidos'])?></td>
                                        <td><?php echo $key?></td>
                                        <td><?php echo money_format('%(#10n', (float)$value['sujetos_iva'])?></td>
                                        <td><?php echo money_format('%(#10n', (float)$value['no_sujetos_iva'])?></td>
                                    </tr>
                                    <tr class="details" style="display: none">
                                        <td colspan="6">
                                            <table class="table inner-table">
                                                <thead>
                                                    <th>Fecha</th>
                                                    <th>Ejecutivo</th>
                                                    <th>Tipo</th>
                                                    <th>Monto</th>
                                                    <th>Comprobante</th>
                                                     <th>Nota</th>
                                                    <th>Opciones</th>
                                                </thead>
                                                <tbody>
                                                    <?php foreach ($value['details'] as $keyDetails => $valueDetails) :?>
                                                        <tr id="<?php echo $valueDetails['idexpedientegasto']?>">
                                                            <td><?php echo date_format(new DateTime($valueDetails['expedientegasto_fecha']), 'd/m/Y H:i')?></td>
                                                            <td><?php echo $valueDetails['empleado_nombre']?></td>
                                                            <td><?php echo $this->translate($valueDetails['expedientegasto_tipo'])?></td>
                                                            <td><?php echo money_format('%(#10n', (float)$valueDetails['expedientegasto_monto'])?></td>
                                                            <td><?php echo $valueDetails['expedientegasto_comprobante']?></td>
                                                            <td><?php echo $valueDetails['expedientegasto_nota']?></td>
                                                            <td><a  class="editar_cargo" data-toggle="tooltip" data-placement="left" title="Editar" href="javascript:;"><i  class="fa fa-pencil"></i></a><a class="eliminar_cargo" data-toggle="tooltip" data-placement="left" title="Eliminar" href="javascript:void(0)"><i class="fa fa-trash-o" style="margin-left: 15px; color: red"></i></i></a></td>
                                                        </tr>
                                                    <?php endforeach;?>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="4"></td>
                                    <td style="text-align: right">Subtotal: </td>
                                    <td><?php echo money_format('%(#10n', (float)$totales['subtotal']).' MXN'?></td>
                                </tr>
                                <tr>
                                    <td colspan="4"></td>
                                    <td style="text-align: right">I.V.A: </td>
                                    <td><?php echo money_format('%(#10n', (float)$totales['iva']).' MXN'?></td>
                                </tr>
                                <tr>
                                    <td colspan="4"></td>
                                    <td style="text-align: right"><b>Total: </b></td>
                                    <td><b><?php echo money_format('%(#10n', (float)$totales['total']).' MXN'?></b></td>
                                </tr>
                                <tr>
                                    <td class="center"><i class="fa fa-plus-circle collapse"></i></td>
                                    <td colspan="3"></td>
                                    <td style="text-align: right">Anticipo: </td>
                                    <td><?php echo money_format('%(#10n', (float)$totales['anticipo']).' MXN'?><a id="add_anticipo_mxn" style="float: right; margin-right: 10px;" href="javascript:;"><i class="fa fa-plus-square"></i></a></td>
                                </tr>
                                <tr class="details" style="display: none">
                                    <td colspan="6">
                                        <table id="table_anticipos_mxn" class="table inner-table">
                                            <thead>
                                                <th>FECHA</th>
                                                <th>MONTO</th>
                                                <th>COMPROBANTE</th>
                                                <th>OPCIONES</th>
                                            </thead>
                                            <tbody>
                                                <?php $anticipo = new Expedienteanticipo();?>
                                                <?php foreach ($anticipos['mxn'] as $anticipo) :?>
                                                <tr id="<?php echo $anticipo->getIdexpedienteanticipo()?>">
                                                    <td><?php echo $anticipo->getExpedienteanticipoFecha('d/m/Y')?></td>
                                                    <td><?php echo money_format('%(#10n', (float)$anticipo->getExpedienteanticipoCantidad())?></td>
                                                    <td><?php echo $anticipo->getExpedienteanticipoComprobante()?></td>
                                                    <td>
                                                        <a class="editar_anticipo" href="javascript:;" title="Editar" data-placement="left" data-toggle="tooltip"><i class="fa fa-pencil"></i></a>
                                                        <a class="eliminar_anticipo" href="javascript:void(0)" title="Eliminar" data-placement="left" data-toggle="tooltip"><i class="fa fa-trash-o" style="margin-left: 15px; color: red"></i></a>
                                                    </td>
                                                </tr>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="4"></td>
                                    <td style="text-align: right">Saldo: </td>
                                    <?php 
                                        $color = 'black';
                                        if($totales['saldo'] < 0 ){$color = 'red';}
                                        elseif($totales['saldo'] > 0 ){$color = 'green';}
                                    ?>
                                    <td style="color:<?php echo $color?>"><?php echo money_format('%#10n', (float)$totales['saldo']).' MXN'?></td>
                                </tr>
                            </tfoot>
                        </table>
                        <?php 
                            $color = 'black';
                            if($totales['utilidad'] < 0 ){$color = 'red';}
                            elseif($totales['utilidad'] > 0 ){$color = 'green';}
                        ?>
                        <p><strong>UTILIDAD: </strong><span style="color:<?php echo $color?>"><?php echo money_format('%10n', (float)$totales['utilidad']).' MXN'?></span></p>
                    </div>
                </div>
            </div>
            <div class="grid simple">
                <div class="grid-title no-border">
                    <div class="grid-title no-border">
                        <h4><span class="semi-bold">Facturación USD</span></h4>
                        <div class="tools">
                            <a id="user-options" class="dropdown-toggle config" href="javascript:;" data-toggle="dropdown"></a>
                            <a class="collapse" href="javascript:;"></a>

                            <ul class="dropdown-menu pull-right" aria-labelledby="user-options" role="menu">
                                <li>
                                    <a id="nuevo_cargo_usd" style="background: none"href="javascript:void(0)"><i class="fa fa-plus"></i> Nuevo cargo</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="grid-body no-border">
                        <?php setlocale(LC_MONETARY, 'en_US'); ?>
                        <table id="table_facturacion" class="table table-striped">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Cargos estimados</th>
                                    <th>Cargos realizados</th>
                                    <th>Conceptos de facturación</th>
                                    <th>Venta sujeta a IVA</th>
                                    <th>Venta no sujeta a IVA</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($facturacion_usd as $key => $value) :?>
                                    <tr class="main"id="<?php echo $value['id']?>">
                                        <td class="center"><i class="fa fa-plus-circle collapse"></i></td>
                                        <td><?php echo money_format('%(#10n', (float)$value['cargos_recibir'])?></td>
                                        <td><?php echo money_format('%(#10n', (float)$value['cargos_conocidos'])?></td>
                                        <td><?php echo $key?></td>
                                        <td><?php echo money_format('%(#10n', (float)$value['sujetos_iva'])?></td>
                                        <td><?php echo money_format('%(#10n', (float)$value['no_sujetos_iva'])?></td>
                                    </tr>
                                    <tr class="details" style="display: none">
                                        <td colspan="6">
                                            <table class="table inner-table">
                                                <thead>
                                                    <th>Fecha</th>
                                                    <th>Ejecutivo</th>
                                                    <th>Tipo</th>
                                                    <th>Monto</th>
                                                    <th>Comprobante</th>
                                                     <th>Nota</th>
                                                    <th>Opciones</th>
                                                </thead>
                                                <tbody>
                                                    <?php foreach ($value['details'] as $keyDetails => $valueDetails) :?>
                                                        <tr id="<?php echo $valueDetails['idexpedientegasto']?>">
                                                            <td><?php echo date_format(new DateTime($valueDetails['expedientegasto_fecha']), 'd/m/Y H:i')?></td>
                                                            <td><?php echo $valueDetails['empleado_nombre']?></td>
                                                            <td><?php echo $this->translate($valueDetails['expedientegasto_tipo'])?></td>
                                                            <td><?php echo money_format('%(#10n', (float)$valueDetails['expedientegasto_monto'])?></td>
                                                            <td><?php echo $valueDetails['expedientegasto_comprobante']?></td>
                                                            <td><?php echo $valueDetails['expedientegasto_nota']?></td>
                                                            <td><a class="editar_cargo" data-toggle="tooltip" data-placement="left" title="Editar" href="javascript:;"><i  class="fa fa-pencil"></i></a><a class="eliminar_servicio" data-toggle="tooltip" data-placement="left" title="Eliminar" href="javascript:void(0)"><i class="fa fa-trash-o" style="margin-left: 15px; color: red"></i></a></td>
                                                        </tr>
                                                    <?php endforeach;?>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="4"></td>
                                    <td style="text-align: right">Subtotal: </td>
                                    <td><?php echo money_format('%(#10n', (float)$totales_usd['subtotal']).' USD'?></td>
                                </tr>
                                <tr>
                                    <td colspan="4"></td>
                                    <td style="text-align: right">I.V.A: </td>
                                    <td><?php echo money_format('%(#10n', (float)$totales_usd['iva']).' USD'?></td>
                                </tr>
                                <tr>
                                    <td colspan="4"></td>
                                    <td style="text-align: right"><b>Total: </b></td>
                                    <td><b><?php echo money_format('%(#10n', (float)$totales_usd['total']).' USD'?></b></td>
                                </tr>
                                <tr>
                                    <td colspan="4"></td>
                                    <td style="text-align: right">Anticipo: </td>
                                    <td><?php echo money_format('%(#10n', (float)$totales_usd['anticipo']).' USD'?><a id="add_anticipo_usd" style="float: right; margin-right: 10px;" href="javascript:;"><i class="fa fa-plus-square"></i></a></td>
                                </tr>
                                <tr>
                                    <td colspan="4"></td>
                                    <td style="text-align: right">Saldo: </td>
                                    <?php 
                                        $color = 'black';
                                        if($totales_usd['saldo'] < 0 ){$color = 'red';}
                                        elseif($totales_usd['saldo'] > 0 ){$color = 'green';}
                                    ?>
                                    <td style="color:<?php echo $color?>"><?php echo money_format('%#10n', (float)$totales_usd['saldo']).' USD'?></td>
                                </tr>
                            </tfoot>
                        </table>
                        <?php 
                            $color = 'black';
                            if($totales_usd['utilidad'] < 0 ){$color = 'red';}
                            elseif($totales_usd['utilidad'] > 0 ){$color = 'green';}
                        ?>
                        <p><strong>UTILIDAD: </strong><span style="color:<?php echo $color?>"><?php echo money_format('%10n', (float)$totales_usd['utilidad']).' USD'?></span></p>
                    </div>
                </div>
            </div>
            <div class="grid simple">
                <div class="grid-title no-border">
                    <div class="grid-title no-border">
                        <h4><span class="semi-bold">Servicios</span></h4>
                        <div class="tools">
                            <a id="user-options" class="dropdown-toggle config" href="javascript:;" data-toggle="dropdown"></a>
                            <a class="collapse" href="javascript:;"></a>

                            <ul class="dropdown-menu pull-right" aria-labelledby="user-options" role="menu">
                                <li>
                                    <a id="nuevo_servicio" style="background: none"href="javascript:void(0)"><i class="fa fa-plus"></i> Nuevo servicio</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="grid-body no-border">
                        <table id="table_servicios" class="table table-striped">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Creación</th>
                                    <th>Servicio</th>
                                    <th>Estatus (Actual)</th>
                                    <th>Opciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $servicio = new Expedienteservicio()?>
                                <?php foreach ($servicios as $servicio) :?>
                                    <!-- OBTENEMOS EL SERVICIO ACTUAL DEL SERVICIO-->
                                    <?php 
                                        $estatus_actual = 'N/D';
                                        $query = ExpedientehistorialQuery::create()->filterByIdexpedienteservicio($servicio->getIdexpedienteservicio())->orderByIdestadoservicio(Criteria::DESC)->findOne();
                                        if(!is_null($query)){
                                            $estatus_actual = $query->getServicioestado()->getServicioestadoNombre();
                                        }
                                    ?>
                                    <tr id="<?php echo $servicio->getIdexpedienteservicio()?>">
                                        <td class="center"><i class="fa fa-plus-circle collapse"></i></td>
                                        <td><?php echo $servicio->getExpedienteservicioFecha('d/m/Y')?></td>
                                        <td><?php echo $servicio->getServicio()->getServicioNombre()?></td>
                                        <td><?php echo $estatus_actual?></td>
                                        <td><a class="eliminar_servicio" href="javascript:void(0)" title="Eliminar" data-placement="left" data-toggle="tooltip"><i class="fa fa-trash-o" style="margin-left: 15px; color: red"></i></a><a class="agregar_historial" href="javascript:void(0)" title="Eliminar" data-placement="left" data-toggle="tooltip"><i class="fa fa-plus-square" style="margin-left: 15px; color: green"></i></a></td>
                                    </tr>
                                    <tr class="details" style="display: none">
                                        <td colspan="5">
                                            <table class="table inner-table">
                                                <thead>
                                                    <th>FECHA/HORA</th>
                                                    <th>ESTATUS</th>
                                                    <th>NOTA</th>
                                                    <th>OPCIONES</th>
                                                </thead>
                                                <tbody>
                                                    <?php foreach ($servicio->getExpedientehistorials() as $valueDetails) :?>
                                                    <tr id="<?php echo $valueDetails->getIdexpedientehistorial()?>">
                                                        <td><?php echo $valueDetails->getExpedientehistorialFecha()?></td>
                                                        <td><?php echo $valueDetails->getServicioestado()->getServicioestadoNombre()?></td>
                                                        <td><?php echo $valueDetails->getExpedientehistorialNota()?></td>
                                                        <td><a class="eliminar_historial" href="javascript:void(0)" title="Eliminar" data-placement="left" data-toggle="tooltip"><i class="fa fa-trash-o" style="margin-left: 15px; color: red"></i></a><a class="editar_historial" href="javascript:void(0)" title="Editar" data-placement="left" data-toggle="tooltip"><i class="fa fa-pencil" style="margin-left: 15px;"></i></a></td>
                                                    </tr>
                                                    <?php endforeach;?>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="grid simple ">
                    <div class="grid-title no-border">
                        <h4><span class="semi-bold">Archivos</span></h4>
                        <div class="tools">
                            <a class="collapse" href="javascript:;"></a>
                        </div>
                    </div>
                    <div class="grid-body no-border">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="row-fluid" style="margin-top: 20px;">
                                    <div class="dropzone" id="mydropzone"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <div class="form-actions">
                <div class="row">
                    <div class="pull-right">
                        <button btn_action="submit" class="btn btn-primary btn-cons" type="button">Guardar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php 
        //echo $this->form()->closeTag(); 
    ?>
</div>
<!--CUSTOM SCRIPT-->
<script src="/js/admin/expedientes/expediente.js"></script>
<!--DROPZONE-->
<script src="/plugins/admin/dropzone/dropzone.js"></script>
<script src="/plugins/admin/download/download.js"></script>
<link rel="stylesheet" type="text/css" href="/plugins/admin/dropzone/css/dropzone.css">
<script type="text/javascript">
    $(document).ready(function() {
        //FORM BIND
        var $form = $('.form_container').expediente({successMessages:<?php echo $successMessages?>});
        $form.formBind(true,<?php echo $files?>);

    });
</script>



