<div class="form_container">
    <ul class="breadcrumb">
        <li>
            <a href="/clientes">Clientes</a>
        </li>
        <li>
            <a href="/clientes/ver/<?php echo $cliente->getIdcliente()?>"><?php echo $cliente->getClienteRazonsocial()?></a>
        </li>
        <li>
            <a href="/clientes/ver/<?php echo $cliente->getIdcliente()?>?active=expedientes">Expedientes</a>
        </li>
        <li>
            <a class="active" href="/clientes/ver/<?php echo $cliente->getIdcliente()?>/expedientes/ver/<?php echo $entity->getIdexpediente()?>"><?php echo $entity->getExpedienteFolio()?></a>
        </li>
    </ul>
    <div class="page-title">
        <h3><span class="semi-bold"><?php echo $entity->getExpedienteFolio()?></span></h3>
    </div>
    <?php 
        //$form->setAttribute('action', '/clientes/ver/'.$cliente->getIdcliente().'/expedientes/nuevo');
        //$form->setAttribute('novalidate', true);
        //$form->setAttribute('enctype', 'multipart/form-data');

        //echo $this->form()->openTag($form); 
    ?>
    <div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4><span class="semi-bold">Información general</span></h4>
                    <div class="tools">
                        <a class="collapse" href="javascript:;"></a>
                    </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <label>Estatus</label>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <input disabled value="<?php echo $entity->getExpedienteEstatus()?>"type="text" class="width-100">
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <label>Fecha de apertura</label>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <input disabled value="<?php echo $entity->getExpedienteFechainicio('d/m/Y')?>"type="text" class="width-100">
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <label>Fecha de cierre</label>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <input disabled value="<?php echo $entity->getExpedienteFechafin('d/m/Y')?>"type="text" class="width-100">
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="pull-right">
                        <button btn_action="submit" class="btn btn-primary btn-cons" type="button">Guardar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php 
        //echo $this->form()->closeTag(); 
    ?>
</div>
<!--CUSTOM SCRIPT-->
<script src="/js/admin/expedientes/expediente.js"></script>

<script type="text/javascript">
    
    $(document).ready(function() {
        
        //FORM BIND
        var $form = $('.form_container').expediente();
        $form.formBind();

    });
</script>



