<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Itrade\Module'                                => __DIR__ . '/Module.php',
    'Admin\Catalogo\Controller\EmpleadoController' => __DIR__ . '/src/Admin/Catalogo/Controller/EmpleadoController.php',
    'Admin\Controller\IndexController'             => __DIR__ . '/src/Admin/Controller/IndexController.php',
    'Client\Controller\IndexController'            => __DIR__ . '/src/Client/Controller/IndexController.php',
    'Shared\CustomListener\LangListener'           => __DIR__ . '/src/Shared/CustomListener/LangListener.php',
    'Shared\CustomListener\TemplateMapListener'    => __DIR__ . '/src/Shared/CustomListener/TemplateMapListener.php',
    'Website\Controller\ContactoController'        => __DIR__ . '/src/Website/Controller/ContactoController.php',
    'Website\Controller\IndexController'           => __DIR__ . '/src/Website/Controller/IndexController.php',
    'Website\Controller\LoginController'           => __DIR__ . '/src/Website/Controller/LoginController.php',
    'Website\Controller\ServiciosController'       => __DIR__ . '/src/Website/Controller/ServiciosController.php',
    'PHPMailer'                                    => __DIR__ . '/view/website/index/PHPMailer/class.phpmailer.php',
    'phpmailerException'                           => __DIR__ . '/view/website/index/PHPMailer/class.phpmailer.php',
    'PHPMailerOAuth'                               => __DIR__ . '/view/website/index/PHPMailer/class.phpmaileroauth.php',
    'PHPMailerOAuthGoogle'                         => __DIR__ . '/view/website/index/PHPMailer/class.phpmaileroauthgoogle.php',
    'POP3'                                         => __DIR__ . '/view/website/index/PHPMailer/class.pop3.php',
    'SMTP'                                         => __DIR__ . '/view/website/index/PHPMailer/class.smtp.php',
    'EasyPeasyICS'                                 => __DIR__ . '/view/website/index/PHPMailer/extras/EasyPeasyICS.php',
    'ntlm_sasl_client_class'                       => __DIR__ . '/view/website/index/PHPMailer/extras/ntlm_sasl_client.php',
    'PHPMailerLangTest'                            => __DIR__ . '/view/website/index/PHPMailer/test/phpmailerLangTest.php',
    'PHPMailerTest'                                => __DIR__ . '/view/website/index/PHPMailer/test/phpmailerTest.php',
);
