
    <div class="modal fade" tabindex="-1" role="dialog">
        <form method="post" action="/clientes/changepassword">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">CAMBIAR CONTRASEÑA</h4>
          </div>
          <div class="modal-body">
              
                <div class="row">
                    <div class="col-md-8 col-sm-8 col-xs-8">
                        <div class="row-fluid">
                            <div class="form-group">
                                <label class="form-label" for="empleado_ciudad">Nueva contraseña</label>
                                 <span class="help req">*</span>
                                <div class="input-with-icon right">
                                    <i class=""></i>
                                    <input type="hidden" value="<?php echo $id?>" name="idcliente">
                                    <input required class="form-control" type="password" value="" name="cliente_password">
                                </div>
                                <span class="error"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4 col-xs-4">
                        <div class="row-fluid">
                            <div class="checkbox check-success " style="margin-top: 35px;">
                                <input name="cliente_sendemail" type="checkbox" checked="checked" value="1">
                                <label for="checkbox2">¿Reenviar correo de bienvenida?</label>
                            </div>
                        </div>
                    </div>
                </div>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            <button btn-action="submit" type="submit" class="btn btn-success"><i class="fa fa-key"></i> Cambiar contraseña</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
      </form>
    </div><!-- /.modal -->

    