<div class="form_container">
    
    <ul class="breadcrumb">
        <li>
            <a href="/clientes"><p>Clientes</p></a>
        </li>
        <li>
            <a class="active" href="/clientes/ver/<?php echo $form->get('idcliente')->getValue()?>"><?php echo $form->get('cliente_razonsocial')->getValue()?></a>
        </li>
    </ul>
    <div class="page-title">
        <h3><span class="semi-bold"><?php echo strtoupper($form->get('cliente_razonsocial')->getValue())?></span></h3>
    </div>
    <?php 
        $form->setAttribute('action', '/clientes/ver/'.$form->get('idcliente')->getValue());
        $form->setAttribute('novalidate', true);
        $form->setAttribute('enctype', 'multipart/form-data');

        echo $this->form()->openTag($form); 
    ?>
    <div class="row">
        <div class="col-md-12">
            <ul id="myTab" class="nav nav-tabs" style="margin-bottom: 15px;">
                <li class="active"><a href="#info">Info</a></li>
                <li><a href="#legal">Perfil legal</a></li>
                <li><a href="#clientes">Clientes        </a></li>
                <li><a href="#proveedores">Proveedores</a></li>
                <li><a href="#expedientes">Expedientes</a></li>
                <li><a href="#files">Archivos</a></li>
            </ul>
            <div class="tab-pane" id="expedientes" style="display: none">
                <div class="grid simple ">
                    <div class="grid-title no-border">
                        <div class="tools">
                            <a id="user-options" class="dropdown-toggle pull-right " href="#" data-toggle="dropdown" style="background: none">
                                <div class="iconset top-settings-dark "></div>
                            </a>
                            <ul class="dropdown-menu pull-right" aria-labelledby="user-options" role="menu">
                                <li>
                                    <a style="background: none"href="/clientes/ver/1/expedientes/nuevo"><i class="fa fa-plus"></i>Nuevo expediente</a>
                                </li>
                            </ul>
                        </div>
                        <br>
                    </div>
                    <div class="grid-body no-border">
                        <table id="table_expedientes" class="table">
                            <thead>
                                <tr>
                                    <th>Fecha de apertura</th>
                                    <th>Tipo</th>
                                    <th>Consignatario</th>
                                    <th>Embarcador</th>
                                    <th>Estatus</th>
                                    <th>Opciones</th>
                                </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="clientes">
                <div class="grid simple">
                    <div class="grid-title no-border">
                        <div class="tools">
                            <a id="user-options" class="dropdown-toggle pull-right " href="#" data-toggle="dropdown" style="background: none">
                                <div class="iconset top-settings-dark "></div>
                            </a>
                            <ul class="dropdown-menu pull-right" aria-labelledby="user-options" role="menu">
                                <li>
                                    <a style="background: none"href="/clientes/ver/1/clientes/nuevo"><i class="fa fa-plus"></i> Registro cliente</a>
                                </li>
                            </ul>
                        </div>
                        <br>
                    </div>
                    <div class="grid-body no-border">
                        <table id="table_clientes" class="table">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Tax ID</th>
                                    <th>Contacto</th>
                                    <th>Teléfono</th>
                                    <th>Opciones</th>
                                </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="info">
            <div class="grid simple ">
                <div class="grid-title no-border">
                    <h4><span class="semi-bold">Información general</span></h4>
                    <div class="tools">
                        <a class="collapse" href="javascript:;"></a>
                    </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_nombrecontacto')) ?>
                                    <span class="help req">*</span>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formHidden($form->get('idcliente')) ?>
                                        <?php echo $this->formText($form->get('cliente_nombrecontacto')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_telefono')) ?>
                                    <span class="help req">*</span>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_telefono')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_celular')) ?>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_celular')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_calle')) ?>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_calle')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_numero')) ?>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_numero')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_interior')) ?>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_interior')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_colonia')) ?>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_colonia')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_codigopostal')) ?>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_codigopostal')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_ciudad')) ?>
                                    <span class="help req">*</span>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_ciudad')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_estado')) ?>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_estado')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_pais')) ?>
                                    <span class="help req">*</span>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_pais')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_cumpleanios')) ?>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_cumpleanios')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>  
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4><span class="semi-bold">Información fiscal</span></h4>
                    <div class="tools">
                        <a class="collapse" href="javascript:;"></a>
                    </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_razonsocial')) ?>  
                                    <span class="help req">*</span>
                                    <div class="input-with-icon right ">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_razonsocial')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_rfc')) ?>  
                                    <span class="help req">*</span>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_rfc')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_callefiscal')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_callefiscal')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_numerofiscal')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_numerofiscal')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_interiorfiscal')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_interiorfiscal')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_codigopostalfiscal')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_codigopostalfiscal')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_coloniafiscal')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_coloniafiscal')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_ciudadfiscal')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_ciudadfiscal')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_estadofiscal')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_estadofiscal')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_paisfiscal')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_paisfiscal')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4><span class="semi-bold">Personal a cargo</span></h4>
                    <div class="tools">
                        <a class="collapse" href="javascript:;"></a>
                    </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('idempleadocomercial')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formSelect($form->get('idempleadocomercial')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('idempleadooperaciones')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formSelect($form->get('idempleadooperaciones')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="grid simple">   
                <div class="grid-title no-border">
                    <h4><span class="semi-bold">Datos de acceso</span></h4>
                    <div class="tools">
                        <a id="user-options" class="dropdown-toggle config" href="javascript:;" data-toggle="dropdown"></a>
                        <a class="collapse" href="javascript:;"></a>
                        <ul class="dropdown-menu pull-right" aria-labelledby="user-options" role="menu">
                            <li>
                                <a id="change_password" style="background: none"href="javascript:void(0)"><i class="fa fa-key"></i> Cambiar contraseña</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row">
                        <div class="col-md-4 col-sm-4 col-xs-4">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_email')) ?>  
                                    <span class="help req">*</span>
                                    <div class="input-with-icon right ">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_email')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
<!--                        <div class="col-md-4 col-sm-4 col-xs-4">
                            <div class="row-fluid">
                                <div class="checkbox check-success " style="margin-top: 35px;">
                                    <input name="cliente_sendemail" type="checkbox" checked="checked" value="1">
                                    <label for="checkbox2">¿Enviar correo de bienvenida?</label>
                                </div>
                            </div>
                        </div>-->
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="pull-right">
                        <button btn_action="submit" class="btn btn-primary btn-cons" type="button">Guardar</button>
                    </div>
                </div>
            </div>
            </div>
            <div class="tab-pane" id="proveedores" style="display: none">
                <div class="grid simple">
                    <div class="grid-title no-border">
                        <div class="tools">
                            <a id="user-options" class="dropdown-toggle pull-right " href="#" data-toggle="dropdown" style="background: none">
                                <div class="iconset top-settings-dark "></div>
                            </a>
                            <ul class="dropdown-menu pull-right" aria-labelledby="user-options" role="menu">
                                <li>
                                    <a style="background: none"href="/clientes/ver/1/proveedores/nuevo"><i class="fa fa-plus"></i> Registro proveedor</a>
                                </li>
                            </ul>
                        </div>
                        <br>
                    </div>
                    <div class="grid-body no-border">
                        <table id="table_proveedores" class="table">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Tax ID</th>
                                    <th>Contacto</th>
                                    <th>Teléfono</th>
                                    <th>Opciones</th>
                                </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="files" style="display: none">
                <div class="grid simple ">
                    <div class="grid-title no-border">
                        <h4><span class="semi-bold">Archivos</span></h4>
                        <div class="tools">
                            <a class="collapse" href="javascript:;"></a>
                        </div>
                    </div>
                    <div class="grid-body no-border">
                        <br>
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="row-fluid" style="margin-top: 20px;">
                                    <div class="dropzone" id="dropzonefiles"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="legal" style="display: none">
                <div class="grid simple ">
                    <div class="grid-title no-border">
                        <h4><span class="semi-bold">Perfil Legal</span></h4>
                        <div class="tools">
                            <a class="collapse" href="javascript:;"></a>
                        </div>
                    </div>
                    <div class="grid-body no-border">
                        <br>
                        <div class="row">
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <li id="cliente_padronimportador">Padrón de importadores (Formato SAT)<span class="legal_validation "><i class=""></i></span></li>
                                <li id="cliente_encargadoconferido">Encargo conferido (Confirmación solicitud vía Internet)<span class="legal_validation "><i class=""></i></span></li>
                                <li id="cliente_r1" >R1 de la empresa<span class="legal_validation "><i class=""></i></span></li>
                                <li id="cliente_r2">R2 en caso de aplicar<span class="legal_validation "><i class=""></i></span></li>
                                <li id="cliente_identificacionrepresentantelegal">Identificación del representante legal<span class="legal_validation "><i class=""></i></span></li>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <li id="cliente_rfcrepresentantelegal">RFC del representante legal<span class="legal_validation "><i class=""></i></span></li>
                                <li id="cliente_actaconstitutiva">Acta constitutiva de la empresa<span class="legal_validation "><i class=""></i></span></li>
                                <li id="cliente_podernotarial">Poder notarial en caso de que aplique<span class="legal_validation "><i class=""></i></span></li>
                                <li id="cliente_cartaencomienda">Carta encomienda hoja membretada<span class="legal_validation "><i class=""></i></span></li>
                                <li id="cliente_comprobantedomicilio">Comprobante de domicilio<span class="legal_validation "><i class=""></i></span></li>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <li id="cliente_comprobanteclabe">Cuenta bancaria CLABE (para reintegrar saldo a favor)<span class="legal_validation "><i class=""></i></span></li>
                                <li id="cliente_archivoszip">Carpeta ZIP archivos: .key, .cer. clave privada y la clave cifrada. (para tramite de ventanilla única) <span class="legal_validation "><i class=""></i></span></li>
                                <li id="cliente_fotografiasdomicilio">Fotografías del domicilio fiscal<span class="legal_validation "><i class=""></i></span></li>
                                
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="row-fluid" style="margin-top: 20px;">
                                    <div class="dropzone" id="mydropzone"></div>
                                </div>
                            </div>
                             <div class="col-sm-12">
                        
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
    <?php 
        echo $this->form()->closeTag(); 
    ?>
</div>
<!--DROPZONE-->
<script src="/plugins/admin/dropzone/dropzone.js"></script>
<script src="/plugins/admin/download/download.js"></script>
<link rel="stylesheet" type="text/css" href="/plugins/admin/dropzone/css/dropzone.css">
<!--CUSTOM SCRIPT-->
<script src="/js/admin/clientes/clientes.js"></script>
<script type="text/javascript">
    
    $(document).ready(function() {
        //FORM BIND
        var $form = $('.form_container').clientes({successMessages:<?php echo $successMessages?>});
        $form.formBind(true,<?php echo $entity?>,<?php echo $files?>);
        
    });
</script>

