<div class="form_container">
    
    <ul class="breadcrumb">
        <li>
            <p>Clientes</p>
        </li>
        <li>
            <a class="active" href="/clientes/nuevo">Registro</a>
        </li>
    </ul>
    <div class="page-title">
        <h3>REGISTRO <span class="semi-bold">CLIENTE</span></h3>
    </div>
    <?php 
        $form->setAttribute('action', '/clientes/nuevo');
        $form->setAttribute('novalidate', true);
        $form->setAttribute('enctype', 'multipart/form-data');

        echo $this->form()->openTag($form); 
    ?>
    <div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4><span class="semi-bold">Información general</span></h4>
                    <div class="tools">
                        <a class="collapse" href="javascript:;"></a>
                    </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_nombrecontacto')) ?>
                                    <span class="help req">*</span>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_nombrecontacto')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_telefono')) ?>
                                    <span class="help req">*</span>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_telefono')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_celular')) ?>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_celular')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_calle')) ?>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_calle')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_numero')) ?>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_numero')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_interior')) ?>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_interior')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_colonia')) ?>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_colonia')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_codigopostal')) ?>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_codigopostal')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_ciudad')) ?>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_ciudad')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_estado')) ?>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_estado')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_pais')) ?>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_pais')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_cumpleanios')) ?>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_cumpleanios')) ?>
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4><span class="semi-bold">Información fiscal</span></h4>
                    <div class="tools">
                        <a class="collapse" href="javascript:;"></a>
                    </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_razonsocial')) ?>  
                                    <span class="help req">*</span>
                                    <div class="input-with-icon right ">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_razonsocial')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_rfc')) ?>  
                                    <span class="help req">*</span>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_rfc')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_callefiscal')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_callefiscal')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_numerofiscal')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_numerofiscal')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_interiorfiscal')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_interiorfiscal')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_codigopostalfiscal')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_codigopostalfiscal')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_coloniafiscal')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_coloniafiscal')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_ciudadfiscal')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_ciudadfiscal')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_estadofiscal')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_estadofiscal')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_paisfiscal')) ?>  
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formText($form->get('cliente_paisfiscal')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4><span class="semi-bold">Datos de acceso</span></h4>
                    <div class="tools">
                        <a class="collapse" href="javascript:;"></a>
                    </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row">
                        <div class="col-md-4 col-sm-4 col-xs-4">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_email')) ?>  
                                    <span class="help req">*</span>
                                    <div class="input-with-icon right ">
                                        <i class=""></i>
                                        <?php echo $this->formEmail($form->get('cliente_email')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-4">
                            <div class="row-fluid">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('cliente_password')) ?>  
                                    <span class="help req">*</span>
                                    <div class="input-with-icon  right">
                                        <i class=""></i>
                                        <?php echo $this->formPassword($form->get('cliente_password')) ?>  
                                    </div>
                                    <span class="error"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-4">
                            <div class="row-fluid">
                                <div class="checkbox check-success " style="margin-top: 35px;">
                                    <input name="cliente_sendemail" type="checkbox" checked="checked" value="1">
                                    <label for="checkbox2">¿Enviar correo de bienvenida?</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-actions">
        <div class="row">
            <div class="pull-right">
                <button btn_action="submit" class="btn btn-primary btn-cons" type="button">Guardar</button>
            </div>
        </div>
    </div>
    <?php 
        echo $this->form()->closeTag(); 
    ?>
</div>
<!--CUSTOM SCRIPT-->
<script src="/js/admin/clientes/clientes.js"></script>
<script type="text/javascript">
    
    $(document).ready(function() {
        
        //FORM BIND
        var $form = $('.form_container').clientes();
        $form.formBind();

    });
</script>

