
    <div class="modal fade" tabindex="-1" role="dialog">
<!--        <form method="post" action="/clientes/changepassword">-->
      <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">SELECCIONE EL ARCHIVO QUE ESTA SUBIENDO</h4>
        </div>
          <div class="modal-body">
              <div class="row">
                  <div class="col-sm-12">
                        <div class="radio radio-success">
                            <p>
                                <input id="padronimportador" checked type="radio" value="padronimportador" name="optionyes">
                                <label for="padronimportador">Padrón de importadores (Formato SAT)</label>
                            </p>
                            <p>
                                <input id="encargadoconferido" type="radio" value="encargadoconferido" name="optionyes">
                                <label for="encargadoconferido">Encargo conferido (Confirmación solicitud vía Internet)</label>
                            </p>
                            <p> 
                                <input id="r1" type="radio" value="r1" name="optionyes">
                                <label for="r1">R1 de la empresa</label>
                            </p>
                            <p> 
                                <input id="r2" type="radio" value="r2" name="optionyes">
                                <label for="r2">R2 de la empresa</label>
                            </p>
                            
                            <p> 
                                <input id="identificacionrepresentantelegal" type="radio" value="identificacionrepresentantelegal" name="optionyes">
                                <label for="identificacionrepresentantelegal">Identificación del representante legal</label>
                            </p>
<!--                            <p> 
                                <input id="rfcarchivo" type="radio" value="rfcarchivo" name="optionyes">
                                <label for="rfcarchivo">RFC de la empresa</label>
                            </p>-->
                            <p> 
                                <input id="rfcrepresentantelegal" type="radio" value="rfcrepresentantelegal" name="optionyes">
                                <label for="rfcrepresentantelegal">RFC del representante legal</label>
                            </p>
                            <p> 
                                <input id="actaconstitutiva" type="radio" value="actaconstitutiva" name="optionyes">
                                <label for="actaconstitutiva">Acta constitutiva de la empresa</label>
                            </p>
                            <p> 
                                <input id="podernotarial" type="radio" value="podernotarial" name="optionyes">
                                <label for="podernotarial">Poder notarial</label>
                            </p>
                            <p> 
                                <input id="cartaencomienda" type="radio" value="cartaencomienda" name="optionyes">
                                <label for="cartaencomienda">Carta encomienda hoja membretada</label>
                            </p>
                            <p> 
                                <input id="comprobantedomicilio" type="radio" value="comprobantedomicilio" name="optionyes">
                                <label for="comprobantedomicilio">Comprobante de domicilio</label>
                            </p>
                            <p> 
                                <input id="comprobanteclabe" type="radio" value="comprobanteclabe" name="optionyes">
                                <label for="comprobanteclabe">Cuenta bancaria CLABE</label>
                            </p>
                            <p> 
                                <input id="archivoszip" type="radio" value="archivoszip" name="optionyes">
                                <label for="archivoszip">Carpeta ZIP archivos: .key, .cer. clave privada y la clave cifrada</label>
                            </p>
                            <p> 
                                <input id="fotografiasdomicilio" type="radio" value="fotografiasdomicilio" name="optionyes">
                                <label for="fotografiasdomicilio">Fotografías del domicilio fiscal</label>
                            </p>
                        </div>
                  </div>
              </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            <button btn-action="submit" type="submit" class="btn btn-success"><i class="fa fa-cloud-upload"></i> Subir archivo</button>
          </div>
        </div>
      </div>
      <!--</form>-->
    </div>
