
    <div class="modal fade" tabindex="-1" role="dialog">
        <form method="post" action="/clientes/changepassword">
      <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">SELECCIONE EL ARCHIVO QUE ESTA SUBIENDO</h4>
        </div>
          <div class="modal-body">
              <div class="row">
<!--                  <div class="col-sm-12">
                       <div class="radio-success">
                           <input name="cliente_legal_file" type="radio" value="cliente_padronimportador">
                            <label>Padrón de importadores (Formato SAT)</label>
                        </div>
                    </div>
                    <div class="col-sm-12">
                       <div class="radio radio-success">
                           <input name="cliente_legal_file" type="radio" value="cliente_padronimportador">
                            <label>Padrón de importadores (Formato SAT)</label>
                        </div>
                    </div>
                    <div class="col-sm-12">
                       <div class="radio radio-success">
                            <input name="cliente_legal_file" type="radio" value="cliente_encargadoconferido">
                            <label>Encargo conferido (Confirmación solicitud vía Internet)</label>
                        </div>
                    </div>
                   <div class="col-sm-12">
                       <div class="radio radio-success">
                            <input name="cliente_legal_file" type="radio" value="cliente_r1">
                            <label>R1 de la empresa</label>
                        </div>
                    </div>
                   <div class="col-sm-12">
                       <div class="radio radio-success">
                            <input name="cliente_legal_file" type="radio" value="cliente_r2">
                            <label>R2 en caso de aplicar</label>
                        </div>
                    </div>
                   <div class="col-sm-12">
                       <div class="radio radio-success">
                            <input name="cliente_legal_file" type="radio" value="cliente_identificacionrepresentantelegal">
                            <label>Identificación del representante legal</label>
                        </div>
                    </div>
                    <div class="col-sm-12">
                       <div class="radio radio-success">
                            <input name="cliente_legal_file" type="radio" value="cliente_rfcarchivo">
                            <label>RFC de la empresa</label>
                        </div>
                    </div>
                  <div class="col-sm-12">
                       <div class="radio radio-success">
                            <input name="cliente_legal_file" type="radio" value="cliente_rfcrepresentantelegal">
                            <label>RFC del representante legal</label>
                        </div>
                    </div>
                  <div class="col-sm-12">
                       <div class="radio radio-success">
                            <input name="cliente_legal_file" type="radio" value="cliente_actaconstitutiva">
                            <label>Acta constitutiva de la empresa</label>
                        </div>
                    </div>
                    <div class="col-sm-12">
                       <div class="radio radio-success">
                            <input name="cliente_legal_file" type="radio" value="cliente_podernotarial">
                            <label>Poder notarial en caso de que aplique</label>
                        </div>
                    </div>
                    <div class="col-sm-12">
                       <div class="radio radio-success">
                            <input name="cliente_legal_file" type="radio" value="cliente_cartaencomienda">
                            <label>Carta encomienda hoja membretada</label>
                        </div>
                    </div>
                    <div class="col-sm-12">
                       <div class="radio radio-success">
                            <input name="cliente_legal_file" type="radio" value="cliente_comprobantedomicilio">
                            <label>Comprobante de domicilio</label>
                        </div>
                    </div>
                    <div class="col-sm-12">
                       <div class="radio radio-success">
                            <input name="cliente_legal_file" type="radio" value="cliente_comprobanteclabe">
                            <label>Cuenta bancaria CLABE</label>
                        </div>
                    </div>
                   <div class="col-sm-12">
                       <div class="radio radio-success">
                            <input name="cliente_legal_file" type="radio" value="cliente_archivoszip">
                            <label>Carpeta ZIP archivos: .key, .cer. clave privada y la clave cifrada</label>
                        </div>
                    </div>
                  <div class="col-sm-12">
                       <div class="radio radio-success">
                            <input name="cliente_legal_file" type="radio" value="cliente_fotografiasdomicilio">
                            <label>Fotografías del domicilio fiscal</label>
                        </div>
                    </div>-->
              </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            <button btn-action="submit" type="submit" class="btn btn-success"><i class="fa fa-cloud-upload"></i>Subir archivo</button>
          </div>
        </div>
      </div><
      </form>
    </div>
